- depends/packages/libevent.mk
- depends/patches/libevent/0001-fix-windows-getaddrinfo.patch
> > TLDR: This poaches a commit from #18287 and adds one more to adjust the Windows version targeted when building libevent. These changes combined should fully fix ipv6 usage with the RPC server on Windows.
> > Binding the RPC server to a ipv6 address does not currently work on Windows.
> > We currently try and bind to `127.0.0.1` and `::1` [by default](https://github.com/bitcoin/bitcoin/blob/master/src/httpserver.cpp#L304).
> > On Windows you'll see lines like this in debug.log:
> > ```shell
> > 2020-06-24T01:49:04Z libevent: getaddrinfo: nodename nor servname provided, or not known
> > 2020-06-24T01:49:04Z Binding RPC on address ::1 port 8332 failed
> > ```
> > 
> > 
> > This issue was bought up in, and supposedly fixed by #18287, however the two people that tested it, both said that …
> build: target Windows 7 when building libevent and fix ipv6 usage

- configure.ac
- src/Makefile.am
- src/Makefile.test.include
- src/addrman.cpp
- src/addrman.h
- src/crypto/chacha20.cpp
- src/crypto/chacha20.h
- src/crypto/common.h
- src/init.cpp
- src/key.cpp
- src/main.cpp
- src/net.cpp
- src/net.h
- src/netbase.cpp
- src/random.cpp
- src/random.h
- src/scheduler.cpp
- src/test/DoS_tests.cpp
- src/test/coins_tests.cpp
- src/test/crypto_tests.cpp
- src/test/pmt_tests.cpp
- src/test/random_tests.cpp
- src/test/scheduler_tests.cpp
- src/test/sighash_tests.cpp
- src/test/skiplist_tests.cpp
- src/test/test_dapscoin.cpp
- src/test/test_random.h
- src/test/util_tests.cpp
- src/txmempool.h
- src/wallet/wallet.cpp
> Since #576 hasn't changed in over a month, here is a reworked version of it.
> So in this PR:
> -We add the memory_cleanse function from upstream, to remove a number of OpenSSL calls.
> -We use OS randomness in addition to OpenSSL randomness (see #576 for why it's needed).
backport of https://github.com/PIVX-Project/PIVX/pull/643 for rpcserver
> [Crypto] Use stronger rand for key generation [rpcserver]

- src/net.h
> This fixes the getaddr response which is crucial for dns-seeders and wallet to find peers. On current code it only checks localhost addr being valid and if its known, while in reality we need to relay the node passed in args.
> 
> Credit to @Aviator-Coding for pointing the bug out and the fix.
backports https://github.com/PIVX-Project/PIVX/pull/1492
> [Net] Relay actual peers instead of localhost on getaddr

- src/wallet/wallet.cpp
- Use Spendable balance when checking Masternode controller Staking Status
> [Fix] Use Spendable balance when checking Masternode controller Staking Status

- src/Makefile.qttest.include
Typo in target flags name causes the position independent flag (-fPIC or
-fPIE) to not be properly passed on when linking the Qt test binary.
On systems that have Qt built with reduced exports, this causes a linker
error.
Gitian and depends based builds aren't affected.
from https://github.com/PIVX-Project/PIVX/pull/541
> [Build] Fix typo in Qt test makefile

- src/rpc/blockchain.cpp
> This adds some extra output to the `getblockchaininfo` RPC command that shows the supermajority status of any soft-forks. Our first one is the BIP65 (CLTV) soft-fork indicated by version 5 blocks (#705).
from https://github.com/PIVX-Project/PIVX/pull/760
> [RPC] Show BIP65 soft-fork progress in getblockchaininfo

- src/chainparams.cpp
- src/chainparams.h
- src/init.cpp
- src/main.cpp
- src/main.h
- Cleanup commented out chainparam items
- Remove some unused chainparam items
- Remove unused function based on Block_Enforce_Invalid()
- Params().Block_Enforce_Invalid() / nBlockEnforceInvalidUTXO = 9902850; //Start enforcing the invalid UTXO's - PRCY is nowhere near this block.
- Remove empty functions
> [Minor Cleanup] Chainparams

- src/init.cpp
> Two changes:
> 
> 1. Guarding `pwalletMain` access from init.cpp, so in the future we could enable pivxd to run without the wallet.
> 2. BugFix: `Wallet::LockCoin` verifying that the MN collateral utxo is in the wallet's map before add it to the locked set. Printing the correct error if the transaction is unknown for the wallet.
from https://github.com/PIVX-Project/PIVX/pull/2218
Item 2 was removed from the PR upstream and replaced with https://github.com/PRCYCoin/PRCYCoin/commit/64db9725d6f5db86a6f2648c76730709346a4367
> [Upstream] Guarding wallet access from init and better MN collateral output lock logging.

- src/init.cpp
> In the shutdown process, stop every thread before dump data to disk, otherwise threads will continue modifying data structures while and after the dump process is being / was executed, ending up not storing all of the data and/or corrupting the node state.
from https://github.com/PIVX-Project/PIVX/pull/2191
> [Upstream] [BugFix] Shutdown, stop threadGroup before dump data to disk.

- src/init.cpp
- src/qt/prcycoin.cpp
- src/qt/walletmodel.cpp
- src/qt/walletmodel.h
> First commit was decoupled from #2131, the topbar staking status polling should not try to refresh data if shutdown was requested.
> Second commit is coming from [bitcoin#12377](https://github.com/bitcoin/bitcoin/pull/12377).
> Third commit is starting the shutdown process and returning early (without starting the import thread) if the best chain cannot be activated during the node's initialization.
from https://github.com/PIVX-Project/PIVX/pull/2228
https://github.com/PRCYCoin/PRCYCoin/commit/fe398cc24040ee7544d621f694c76d19c07979d5 was slightly modified to only add the function, it is not currently in use, but can be useful for future
> [Upstream] Fixing few shutdown problems

- src/chainparams.cpp
- src/chainparams.h
- src/main.cpp
BIP65 was enabled with block version 5. It makes sense to save a bit of
performance by simply checking for height activation instead of looking
for a super majority.
from https://github.com/PIVX-Project/PIVX/pull/1067
> [Upstream] [Node] Replace IsSuperMajority with height checks

- src/net.cpp
- src/poa.cpp
These become permanent after Friday, March 26, 2021 12:00:00 AM (GMT) and no longer require a time check
> Remove Timed Ban/PoA Fix

- src/chainparams.cpp
- src/chainparams.h
- src/main.cpp
- src/miner.cpp
- src/poa.cpp
Now that the time has passed, we can use a block height instead
Fixes syncing from 0
> [Fix] Change PoAPaddingTime to PoAPaddingBlock - Sync Fix

- src/rpc/rawtransaction.cpp
- Show "Wallet is Locked" instead of incorrect decoded_amount
- Add `getrawtransaction TXID 2` RPC - which will EnsureWalletIsUnlocked() first
> [Wallet] Hide Incorrect Values When Locked

- src/qt/forms/revealtxdialog.ui
- src/qt/historypage.cpp
- src/qt/revealtxdialog.cpp
- src/qt/revealtxdialog.h
For some reason the amount was never available on the Transaction Details dialog, makes more sense to have it
Old
New
> [QT] Add amount to TX Reveal Dialog

- src/qt/guiutil.cpp
> From [bitcoin#11156](https://github.com/bitcoin/bitcoin/pull/11156)
> 
> > on macOS:
> > listSnapshot was leaking in findStartupItemInList()
> > bitcoinAppUrl was leaking in [Get|Set]StartOnSystemStartup()
from https://github.com/PIVX-Project/PIVX/pull/2374
> [Upstream] [Backport] Fix memory leaks in qt/guiutil.cpp

- configure.ac
- contrib/devtools/symbol-check.py
- src/compat/glibc_compat.cpp
> Bump up the minimum supported libc version to 2.17, which is necessary moving forward with sapling work.
> 
> 2.17 was chosen as that is what CentOS 7 includes, which won't reach EOL until 2024.
> 
> Also included here are a couple cleanups for checks or backwards compatibility code that are rendered moot with the libc version bump.
from https://github.com/PIVX-Project/PIVX/pull/1770
[Note: we do not have sapling, but we are cleaning up the depends/build processes]
> [Upstream] [Build] Bump minimum libc to 2.17 for release binaries

- depends/builders/darwin.mk
> Fixes errors like `fatal error: 'unistd.h' file not found` when building depends on macOS.
> 
> Coming from [bitcoin#17118](https://github.com/bitcoin/bitcoin/pull/17118).
from https://github.com/PIVX-Project/PIVX/pull/2350
> [Upstream] [build] depends macOS: point --sysroot to SDK

- src/bignum.h
- src/crypter.cpp
- src/ecwrapper.cpp
- src/qt/paymentrequestplus.cpp
> What prompted me to address the situation is related to issue https://github.com/PIVX-Project/PIVX/issues/149
> Let's give a bit of context:
> In bitcoin, openssl was used in consensus critical code. Following the infamous heartbleed vulnerability discovered in openssl code, libressl was created as a fork to refactor and improve ssl code. To this day, libressl is used as default instead of openssl in the os openBSD. As far as crypto are concerned: the openssl hotfix was integrated into bitcoin promptly. The change in consensus code triggered a fork. bip 66 was then decided, removing openssl code from consensus critical area and using custom implementation by core team instead. This bip was backported in dash commit [3d004ab](https://github.com/PIVX-Project/PIVX/commit/3d004ab81952916cfc3 …
> [Upstream] [Consensus] Allow for compilation with OpenSSL 1.1

- src/activemasternode.cpp
- src/chainparams.cpp
- src/chainparams.h
- src/main.cpp
- src/masternodeman.cpp
- src/obfuscation.cpp
- src/wallet/wallet.cpp
Make masternode collateral amount a consensus param
A bit of a cherry pick from https://github.com/PIVX-Project/PIVX/pull/2296
https://github.com/PIVX-Project/PIVX/pull/2296/commits/86dcf69e392ac081d97c1cb68c6b733113c5421a
This makes it easier for modifying the MN Collateral in the future, which we have briefly discussed
> [Consensus] Make masternode collateral amount a consensus param (chainparams)

- src/chainparams.cpp
- src/net.cpp
- src/poa.cpp
- Fix height in CheckPoAContainRecentHash
- Change Hard Fork block to 365000
- Restore checks for Hard Fork
- Ban v1.0.0.7 after Hard Fork
- Add "poa" logs for IsFixedAudit/IsWrongAudit `LogPrint("poa", "%s: block %d passed in as nHeight\n", __func__, nHeight);`
> Hard Fork Hot Fix

- src/chainparams.cpp
To allow more time for exchanges/hosts to update, we will move the Hard Fork block to 370,000
> [Hard Fork] Change Hard Fork block to 370000

- src/chainparams.cpp
With the addition of a few Consensus changes, we have had to move the Hard Fork block from 370k to 375k to give Exchanges, partners, and users at least 10k blocks to update from release.
> [Hard Fork] Change Hard Fork block to 375000

- src/wallet/wallet.cpp
> When build with `--enable-debug` the linker complains about a missing `boost::gregorian` dependency which is not really needed.
> 
> This PR removes this dependency, because, as we all know, with each BOOST-dependency somewhere a Unicorn dies...
> 
> It also addresses #601
> Thanks and kudos to @FornaxA for finding the problem!
from https://github.com/PIVX-Project/PIVX/pull/605
> [Upstream] [Build] Remove unnecessary BOOST dependency

- share/qt/Info.plist.in
> Straightforward change, preventing any macOS dark mode theme forced change.
> Coming from btc [cf2f430](https://github.com/PIVX-Project/PIVX/commit/cf2f4306fe26305b24bba8833af845ada3a42ec8)
from https://github.com/PIVX-Project/PIVX/pull/1122
> [Upstream] [GUI][Backport] Explicitly disable "Dark Mode" appearance on macOS

- configure.ac
- src/qt/bitcoingui.cpp
- src/qt/bitcoingui.h
- src/qt/guiutil.cpp
- src/qt/guiutil.h
- src/qt/macdockiconhandler.h
- src/qt/macdockiconhandler.mm
One of a number of PRs needed to get our Mac builds more up to date:
> Updating `MacDockIconHandler` to latest upstream. Fixing #1512 .
> 
> Back ported PRs:
> 
> #### gui: Add GUIUtil::bringToFront [14123](https://github.com/bitcoin/bitcoin/pull/14123):
> ```
> The sequence show -> raise -> activateWindow is factored out to the new function GUIUtil::bringToFront where a macOS fix is added in order to fix #13829.
> 
> Also included:
> 
> simplification of BitcoinGUI::showNormalIfMinimized
> ```
> 
> #### qt: Replace objc_msgSend() function calls with the native Objective-C syntax [16720](https://github.com/bitcoin/bitcoin/pull/16720):
> ```
> Changes in Xcode 11 Objective-C Runtime cause an error (#16387) during building on MacOS 10.15 Catalina.
> 
> This PR fixes this issue by replacing …
```
> [Upstream] [GUI] Back port latest MacOS dock icon handler.

- src/wallet/walletdb.cpp
> Prevent file access collisions and possible file corruption by refusing
> to overwrite the current wallet in use.
> 
> On the off chance that a user attempts to use `backupwallet` in a way that the destination is the same as the source, an error will be returned instead of an attempted backup.
from https://github.com/PIVX-Project/PIVX/pull/711
> [Upstream] [RPC] Don't allow backupwallet to overwrite the wallet-in-use

- src/qt/guiutil.cpp
- src/qt/guiutil.h
> Built on top of #1515, only last commit counts for this.
> 
> When MacOS has no default app to open *.conf and *.log throws an error instead of try to open them with a text editor. This PR solves the issue.
> 
> Coming from btc@[16044](https://github.com/bitcoin/bitcoin/pull/16044)
First commit is a cherry pick of https://github.com/PIVX-Project/PIVX/commit/680d2ddda15e0251d2b54e12c169595fce29d1c2 to match the conversion from void to bool
from https://github.com/PIVX-Project/PIVX/pull/1516
> [Upstream] [GUI] MacOS fix open files with no default app.

- src/amount.cpp
- src/amount.h
- src/init.cpp
- src/qt/askpassphrasedialog.cpp
- src/qt/bitcoinunits.cpp
> Closes #1317
> Ref: [#1209 (comment)](https://github.com/PIVX-Project/PIVX/pull/1209#discussion_r360828832)
> 
> My nit was exclusively about `extern const std::string CURRENCY_UNIT` which is defined here (in `amount.*`) but never actually used. It should be used to replace many instances of the explicit string "PIV" in the code, so I suggest we define it when this is addressed (rather than having unused extern variables in the meantime).
Nice refactor from Upstream to smartly use CURRENCY_UNIT when possible
from https://github.com/PIVX-Project/PIVX/pull/1547
> [Upstream] [Refactor] Define constant string variable for currency unit 

- src/tinyformat.h
- src/util.h
> this backports the following pull requests from upstream bitcoin:
> 
> * [tinyformat: force USE_VARIADIC_TEMPLATES bitcoin/bitcoin#8000](https://github.com/bitcoin/bitcoin/pull/8000) ([0fa578f](https://github.com/PIVX-Project/PIVX/commit/0fa578f598d3ada97d3e89f1bab967a480ef539f), [6837887](https://github.com/PIVX-Project/PIVX/commit/68378877e8b6cfeade4ce5987c621064be1c22b3))
> 
> > Now that we started using c++11, force use of variadic templates.
> > The autodetection may be wonky on some compilers, see discussion here and is unnecessary for us anyhow.
> 
> * [util: Update tinyformat bitcoin/bitcoin#8274](https://github.com/bitcoin/bitcoin/pull/8274) ([500dfee](https://github.com/PIVX-Project/PIVX/commit/500dfeed876660a209b2e833473f747bb293d4d0), …
> [Upstream] [Util] tinyformat / LogPrint backports

- src/init.cpp
> Implemented on top of:
> 
> 
> Backports [bitcoin#10123](https://github.com/bitcoin/bitcoin/pull/10123)
> 
> > setting `-debug` can lead to very noisy debug.logs with subcomponents filling up the log file. See for example https://travis-ci.org/bitcoin/bitcoin/jobs/216767286 where there are hundreds of libevent debug logs.
> 
> This commit adds an option to exclude certain components from debug logging. The usage is:
> 
> ```
> pivxd -debug -debugexclude=<component1> -debugexclude=<component2> ...
> ```
> 
> This finally reduces spammy logs in the …
> [Upstream] [Core] Add -debugexclude option

- src/init.cpp
- src/util.cpp
- src/util.h
> implemented on top of
> 
> * [x]  [[Core] Add -debugexclude option #1439](https://github.com/PIVX-Project/PIVX/pull/1439)
> 
> Backports [bitcoin#6149](https://github.com/bitcoin/bitcoin/pull/6149)
> 
> > Prevents stomping on debug logs in datadirs that are locked by other
> > instances and lost parameter interaction messages that can get wiped by
> > ShrinkDebugFile().
> > The log is now opened explicitly and all emitted messages are buffered
> > until this open occurs.  The version message and log cut have also been
> > moved to the earliest possible …
> [Upstream] [Util] Buffer log messages and explicitly open logs

- src/httpserver.cpp
- src/httpserver.h
- src/init.cpp
- src/rpc/client.cpp
- src/rpc/misc.cpp
- src/rpc/server.cpp
- src/rpc/server.h
- src/util.cpp
- src/util.h
> Implemented on top of:
> 
> * [x]  [[Core] Add -debugexclude option #1439](https://github.com/PIVX-Project/PIVX/pull/1439)
> * [x]  [[Util] Buffer log messages and explicitly open logs #1450](https://github.com/PIVX-Project/PIVX/pull/1450)
> 
> Backports [bitcoin#10150](https://github.com/bitcoin/bitcoin/pull/10150)
> 
> > Adds an RPC to get/set active logging categories.
> > First commit allows all categories except libevent to be reconfigured during runtime.
> > Second commit modifies InitHTTPServer() to allow leveldb logging to be reconfigured during …
> [Upstream] [RPC] Add logging RPC

- src/httpserver.cpp
- src/httpserver.h
- src/init.cpp
- src/rpc/client.cpp
- src/rpc/misc.cpp
- src/rpc/server.cpp
- src/rpc/server.h
- src/util.cpp
- src/util.h
- test/functional/feature_logging.py
> Implemented on top of
> 
> * [x]  [[Core] Add -debugexclude option #1439](https://github.com/PIVX-Project/PIVX/pull/1439)
> * [x]  [[Util] Buffer log messages and explicitly open logs #1450](https://github.com/PIVX-Project/PIVX/pull/1450)
> * [x]  [[RPC] Add logging RPC #1451](https://github.com/PIVX-Project/PIVX/pull/1451)
> 
> Only last 4 commits are relevant to this PR. Backports [bitcoin#11781](https://github.com/bitcoin/bitcoin/pull/11781)
> 
> > This patch adds an option to configure the name and/or directory of the debug log file.
> > The user can …
> [Upstream] [Init] Add -debuglogfile option

- src/Makefile.am
- src/activemasternode.cpp
- src/httpserver.cpp
- src/httpserver.h
- src/init.cpp
- src/kernel.cpp
- src/logging.cpp
- src/logging.h
- src/main.cpp
- src/masternode-budget.cpp
- src/qt/transactiondesc.cpp
- src/rpc/misc.cpp
- src/test/test_prcycoin.cpp
- src/timedata.cpp
- src/util.cpp
- src/util.h
- src/wallet/wallet.cpp
> Implemented on top of:
> 
> * [x]  [[Core] Add -debugexclude option #1439](https://github.com/PIVX-Project/PIVX/pull/1439)
> * [x]  [[Util] Buffer log messages and explicitly open logs #1450](https://github.com/PIVX-Project/PIVX/pull/1450)
> * [x]  [[RPC] Add logging RPC #1451](https://github.com/PIVX-Project/PIVX/pull/1451)
> * [x]  [[Init] Add `-debuglogfile` option #1455](https://github.com/PIVX-Project/PIVX/pull/1455)
> 
> This creates a new class BCLog::Logger to encapsulate all global logging configuration and state.
> 
> Adapted from
> 
> * …
> [Upstream] [Util] Refactor logging code into a global object

- src/logging.cpp
- src/logging.h
- src/masternode.cpp
- src/masternodeman.cpp
> mnping logs are very spammy. Introduce a dedicated BCLog category for them (`MNPING`), so they can be optionally turned off (whilst still keeping the `MASTERNODE` category logged).
from https://github.com/PIVX-Project/PIVX/pull/1822
https://github.com/PRCYCoin/PRCYCoin/commit/7734ba2fef129d1c5a672a820e9d81a84f1bc34e is from https://github.com/PIVX-Project/PIVX/pull/1860
> [Upstream] [Refactor] Dedicated logging category for masternode pings

- src/main.cpp
This commit cleans up the excessive logging from ProcessMessage.
coming from this commit: https://github.com/furszy/PIVX/commit/d07e1a80b900161dec5f388fcd5ed1a7ec537524
(it was merged as part of another Pull Request that we have not completed yet)
> [Upstream] [Output] Log network message receives as "net" debug category

- configure.ac
> * When aiming for glibc compatibility, don't use thread_local.
>   Ensures we're meeting the backwards compatibility target with gitian.
> * Add a flag --enable-threadlocal, which, when specified, will
>   enable/disable thread_local regardless of the value of glibc_compat.
> * MingW, Darwin, and FreeBSD have a buggy thread_local, don't use it.
Simple backport
from https://github.com/PIVX-Project/PIVX/pull/1390
> [Upstream] [Build] Add flag for enabling thread_local

- Makefile.am
- depends/Makefile
- depends/hosts/default.mk
- depends/packages/boost.mk
- depends/packages/native_b2.mk
- depends/packages/packages.mk
> Backports the following upstream PRs to clean up and update the Boost dependency
> 
> * [build: Add variable printing target to Makefiles bitcoin/bitcoin#17087](https://github.com/bitcoin/bitcoin/pull/17087)
> * [depends: fix boost mac cross build with clang 9+ bitcoin/bitcoin#17231](https://github.com/bitcoin/bitcoin/pull/17231)
> * [depends: Consistent use of package variable bitcoin/bitcoin#17928](https://github.com/bitcoin/bitcoin/pull/17928)
> * [build: Propagate well-known vars into depends bitcoin/bitcoin#18820](https://github.com/bitcoin/bitcoin/pull/18820)
> * [depends: Split boost into build/host packages + bump + cleanup bitcoin/bitcoin#19764](https://github.com/bitcoin/bitcoin/pull/19764)
from https://github.com/PIVX-Project/PIVX/pull/2331
We have 2 commits less: …
> [Upstream] [Depends] Bump boost to 1.71.0 and optimize flow

- depends/config.guess
- depends/config.sub
> Allows the depends system to properly identify M1 Mac systems as `aarch64-apple-darwin`.
from https://github.com/PIVX-Project/PIVX/pull/2522
> [Upstream] [Depends] Use latest config guess/sub

- depends/packages/qt.mk
> Hard-set arm64 device arch for apple silicon (aarch64) builds in order to ensure native binaries are all aarch64 compatible.
> 
> Note: At the moment, this only works for native depends builds on M1 CPUs as we're not yet at the point of supporting cross-compiling to aarch64-apple builds; Other builds are unaffected by this change.
from https://github.com/PIVX-Project/PIVX/pull/2582
> [Upstream] [Depends] Fix Qt builds for M1 apple builds

- src/net.cpp
This was causing the crash on macOS after #142
> [Fix] Missed return in OpenNetworkConnection

- src/compat/byteswap.h
- src/qt/guiutil.cpp
- src/qt/guiutil.h
- src/qt/prcycoin.cpp
- src/util.cpp
> Straightforward update for the `guiutil` files. First commit removes unused `TableViewLastColumnResizingFixer` and `DHMSTableWidgetItem` from `guiutil.h/cpp`. Second and third commit comes from [bitcoin#15208](https://github.com/bitcoin/bitcoin/pull/15208). Fourth commit comes from [bitcoin#14801](https://github.com/bitcoin/bitcoin/pull/14801).
from https://github.com/PIVX-Project/PIVX/pull/2380
We drop the first commit as we still use `TableViewLastColumnResizingFixer` and `DHMSTableWidgetItem` in a few places
> [Upstream] [Cleanup] guiutils cleanup + fix memory mismanagement

- src/qt/askpassphrasedialog.cpp
- src/qt/askpassphrasedialog.h
- src/qt/bitcoingui.cpp
- src/qt/forms/askpassphrasedialog.ui
- src/qt/masternodelist.cpp
- src/qt/optionspage.cpp
- src/qt/overviewpage.cpp
- src/qt/sendcoinsdialog.cpp
- src/qt/walletmodel.cpp
- src/qt/walletmodel.h
- src/qt/walletview.cpp
- src/wallet/rpcwallet.cpp
- src/wallet/wallet.cpp
- src/wallet/wallet.h
Rename Unlocked For Anonymization Only to Unlocked For Staking Only
- UnlockedForAnonymizationOnly to UnlockedForStakingOnly
- fWalletUnlockAnonymizeOnly to fWalletUnlockStakingOnly
- Mode::UnlockAnonymize to Mode::UnlockStaking
- anonymizationCheckBox to stakingCheckBox
We do not have Anonymization, but this can be used in future to set a wallet unlocked for Staking only to prevent sending, etc.
> [Trivial] Rename Unlocked For Anonymization Only to Unlocked For Staking Only

- src/qt/prcycoin.cpp
Hide Unlock Wallet when launched with -min
- You still need to login to use it, but the password box is not shown when launched with these parameters
- Everything balance related is still hidden until unlocked
> [Qt] Hide login when launched with -min

- src/qt/prcycoin.cpp
When using the -min flag, the node would not start to sync because this was not being emitted. Move it so it will be emitted in any cases.
> [Qt] Move requestedRegisterNodeSignal() outside if statement

- src/rpc/misc.cpp
- src/rpc/server.cpp
- src/rpc/server.h
Similar to validateaddress (which is disabled as it does not work with Stealth addresses), verifies that a Stealth Address is valid.
> [RPC] Add validatestealthaddress

- src/qt/bitcoingui.cpp
- src/qt/forms/optionspage.ui
- src/qt/historypage.cpp
- src/qt/historypage.h
- src/qt/optionspage.cpp
- src/qt/optionspage.h
- src/qt/overviewpage.cpp
- src/qt/overviewpage.h
- src/qt/sendcoinsdialog.cpp
- src/qt/walletframe.cpp
- src/qt/walletframe.h
Some useful settings for the QT wallet when being used on a shared PC or just for extra privacy.
- Hide Balance when unlocked for Staking
- Lock "Send"tab when unlocked for Staking
New Settings:
Overview when in use:
Attempts to access Send tab when setting enabled is logged in debug.log
> [Qt] New Privacy Settings

- src/main.cpp
This one slid through when changing the Logging categories recently, so move additional GetSeeSaw log to "supply" category
ex. `GetSeeSaw: moneysupply=60666317.50, nodecoins=1200000.00 `
> [Trivial] Move additional GetSeeSaw log to "supply" category

- .github/workflows/prcy-build-factory.yml
- Add Linux job for building with apt installed packages vs depends
- We previously had issues building this way due to compile errors. This is now fixed with recent updates to the depends/build system.
- Cleanup unused packages
- We were installing a lot of unused packaging, bloating the artifact sizes, as well as slowing down the build process.
Next, will look at building the AppImage with Actions so that all release builds can be completed there. Currently built manually on Ubuntu 16 VM.
Note: We can't use Ubuntu 16 as was used previously as that GitHub Actions runner is no longer available. Achieve the same in Ubuntu 18.
> [GitHub Actions] Various updates 

- src/qt/forms/receivecoinsdialog.ui
- src/qt/receivecoinsdialog.cpp
- src/qt/receivecoinsdialog.h
Add generateintegratedaddress button
Currently the only way to generate an integrated address is via Debug Console/Daemon - add a button as seen below
This could potentially be expanded upon in future with things such as
- Optional popup of address + Payment ID - allow the user to copy from there
- Expansion of the History screen to display Payment IDs
> [Qt] Add generateintegratedaddress button

- src/qt/forms/revealtxdialog.ui
- src/qt/historypage.cpp
- src/qt/revealtxdialog.cpp
- src/qt/revealtxdialog.h
- Add PaymentID to revealtxdialog Dialog
- if there is no Payment ID, that line will be hidden
> [Qt] Add PaymentID to revealtxdialog Dialog

- .github/workflows/prcy-build-factory.yml
With the number of test builds increasing, better to add the (short) commit hash to the filenames to be easier to tell them apart.
Runs on all branches except master
> [GitHub Actions] Append Commit Hash to Development Builds

- src/rpc/client.cpp
- src/rpc/server.cpp
- src/rpc/server.h
- src/wallet/rpcwallet.cpp
`sendalltostealthaddress StealthAddress`
Sends the remaining balance of the wallet to an address
Makes it much easier to sweep an old wallet
> [RPC] Add sendalltostealthaddress

- src/qt/receivecoinsdialog.cpp
Add Generated Integrated Address to dropdown when the user clicks the `+` icon
> [Qt] Add Generated Integrated Address to dropdown on "Receive" tab

- src/qt/bitcoingui.cpp
- src/qt/bitcoingui.h
Our FAQ has been moved to a Knowledge Base, rename and fix broken link
> [Qt] Rename FAQ to Knowledge Base and fix link

- src/qt/forms/receivecoinsdialog.ui
- src/qt/receivecoinsdialog.cpp
- src/qt/receivecoinsdialog.h
- Fixes Request Payment Dialog
- Adds button to Remove Integrated Address
- Adds ability to add label to Integrated Addresses
- Cleanup/simplify code around Master Accounts (commented old code)
- Copy currently displayed address from the Dropdown instead of Master Account all the time
- Remove code re: AllMyPublicAddresses -> currently unused
> [Qt] Request Payment/Integrated Address updates

- src/main.cpp
- src/masternode-budget.cpp
- src/masternode-payments.cpp
- src/masternode-sync.cpp
- src/masternodeman.cpp
- src/net.cpp
- src/protocol.cpp
- src/protocol.h
- src/rpc/budget.cpp
- src/swifttx.cpp
- src/wallet/rpcwallet.cpp
- src/wallet/wallet.cpp
- src/wallet/wallet.h
Another one as part of https://github.com/PRCYCoin/PRCYCoin/issues/4
> Ported from [bitcoin#7181](https://github.com/bitcoin/bitcoin/pull/7181) with layer 2 messages in a followup commit, then ran both commits through `clang-format-diff.py`
> 
> > * Avoids string typos (by making the compiler check)
> > * Makes it easier to grep for handling/generation of a certain message type
> > * Refer directly to documentation by following the symbol in IDE
> > * Move list of valid message types to protocol.cpp:
> >   protocol.cpp is a more appropriate place for this, and having
> >   the array there makes it easier to keep things consistent.
from https://github.com/PIVX-Project/PIVX/pull/1542
We leave out the `Apply clang-format` commit here as we will be applying it in it's own PR.
> [Upstream] [Net] Add and document network messages in protocol.h

- src/activemasternode.cpp
- src/addrman.cpp
- src/addrman.h
- src/init.cpp
- src/main.cpp
- src/masternodeman.cpp
- src/net.cpp
- src/net.h
- src/obfuscation-relay.cpp
- src/protocol.cpp
- src/protocol.h
- src/rpc/masternode.cpp
- src/test/DoS_tests.cpp
- src/test/addrman_tests.cpp
- src/test/net_tests.cpp
Another one as part of https://github.com/PRCYCoin/PRCYCoin/issues/4
> Backport of [bitcoin#7749](https://github.com/bitcoin/bitcoin/pull/7749). This is next in line for #1374.
> 
> Original description:
> 
> > At this point, we do not:
> > 
> > * check that relayed/stored addr messages have the NODE_NETWORK bit set.
> > * check that nodes selected for outbound connection have NODE_NETWORK advertized.
> > * check that the nServices flag in the "version" message by a node corresponds to what we expected when deciding to connect to it.
> > * store the updated nServices flag from the "version" message in addrman.
> > 
> > Fix this.
from https://github.com/PIVX-Project/PIVX/pull/1616
> [Upstream] [P2P] Enforce expected outbound services

- src/chainparams.cpp
- src/chainparams.h
- src/net.cpp
Another one as part of https://github.com/PRCYCoin/PRCYCoin/issues/4
> Backport of [bitcoin#8208](https://github.com/bitcoin/bitcoin/pull/8208) based on top of #1616 (Only the last commit is important here). Part of #1374.
> 
> Original Description:
> 
> > Any flag set in nRelevantServices would propagate to all CAddress results retrieved from the DNS seed, even if that DNS seed does not support filtering.
> > Fix this by making the name adaptation function also update the passed in flags.
> > Furthermore, move that from from DNSSeedData to net. Structs in chainparams should be data only.
from https://github.com/PIVX-Project/PIVX/pull/1618
> [Upstream] [P2P] Do not set extra flags for unfiltered DNS seed results

- src/net.cpp
- src/net.h
- src/netbase.cpp
- src/rpc/net.cpp
Another one as part of #4
> Partial backport of [bitcoin#8113](https://github.com/bitcoin/bitcoin/pull/8113) as part of #1374.
> 
> Original Description:
> 
> > * Maintains consistency between ThreadOpenAddedNodeConnections and getaddednodeinfo, without any DNS resolving from RPC.
> > * Deals with the use case of added names whose IP mapping changes over time (switching over to the new IP only when the connection to the old one closes, though).
> > * Gets rid of the fDns argument to getaddednodeinfo (turning it into a dummy)
> > * Simplifies the code significantly by introducing a shared GetAddedNodeInfo in net.cpp.
> > * The existing addnode logic that tries all resolved addresses for a name is pushed down into ConnectSocketByName (picking at random).
> > * ~The existing addnode logic to …
> [Upstream] [P2P][RPC] Rework addnode behaviour

- src/activemasternode.cpp
- src/chainparams.h
- src/main.cpp
- src/masternode-sync.cpp
- src/masternode.cpp
- src/masternodeman.cpp
- src/net.cpp
> This removes many explicit checks `Params().NetworkID() != CBaseChainParams::REGTEST` / `Params().NetworkID() == CBaseChainParams::REGTEST` making the code more readable.
https://github.com/PIVX-Project/PIVX/pull/1282
Used in an upcoming PR.
> [Upstream] [Core][Cleanup] Add IsRegTestNet() function in chainparams

- src/main.h
- src/txdb.h
- src/undo.h
> This is PR is the second part of breaking up #1209 into individual narrow-focused PRs. Original commit was cherry-picked from @barrystyle's initial pre-squashed branch (reference branch is at https://github.com/Fuzzbawls/PIVX/commits/pr-1209)
> 
> Here `CDiskTxPos` and `CBlockUndo` are moved out of `main.h` into more appropriate files, namely `txdb.h` and `undo.h`.
from https://github.com/PIVX-Project/PIVX/pull/1319
> [Upstream] [Refactor] Move CDiskTxPos/CBlockUndo to txdb.h/undo.h respectively

- contrib/prcycoin-qt.pro
- src/Makefile.am
- src/consensus/tx_verify.cpp
- src/consensus/tx_verify.h
- src/main.cpp
- src/main.h
- src/miner.cpp
- src/test/script_P2SH_tests.cpp
- src/test/sighash_tests.cpp
- src/test/transaction_tests.cpp
- src/wallet/wallet.h
> This is PR is the third part of breaking up #1209 into individual narrow-focused PRs. Original commit(s) were cherry-picked from @barrystyle's initial pre-squashed branch and then re-squashed (reference branch is at https://github.com/Fuzzbawls/PIVX/commits/pr-1209)
> 
> Input commits: [Fuzzbawls@90950f1](https://github.com/Fuzzbawls/PIVX/commit/90950f18ea2553c0e21aebd58ecb73d1f521da59) [Fuzzbawls@10b7566](https://github.com/Fuzzbawls/PIVX/commit/10b756628297d7ce5e73b7461af12993c5326fd4)
> 
> This Moves the basic (non-zerocoin) transaction validation checks away from main.h(cpp) and into the `consensus` subdir. Code move only, no changes to functionality.
> 
> This PR conflicts minorly with #1319, and will need to be rebased once that PR is merged, but reviewing is possible now as the …
> [Upstream] [Refactor] Move transaction checks out to consensus/tx_verify.cppUpstream refactor tx verification new

- src/masternode.cpp
- src/masternode.h
> The new message format was introduced with protocol 70914 (v3.1.0) and the old message was retained in order to be able to still check against it during the update. After 4 more protocol upgrades we can safely assume that no masternode has MNANNOUNCE message signed with the old format so we can remove it from the code.
> 
> The function `GetOldStrMessage()` is removed and `GetNewStrMessage()` is renamed to `GetStrMessage()`.
from https://github.com/PIVX-Project/PIVX/pull/1001
Removing some duplicate and unnecessary code.
We actually never introduced a different message format, but have them as 2 duplicate functions.
- Our `GetOldStrMessage === GetNewStrMessage` anyway
- Due to above, there was a double check of the same `strMessage` in `obfuScationSigner.VerifyMessage`
- Use …
> [Upstream] [Consensus] Remove Old message format in CMasternodeBroadcast

- src/main.cpp
- src/masternode-budget.cpp
- src/miner.cpp
- Fix PoA Mining on Testnet
- Wasn't checking block height for change in nReward at Params().HardFork()
- Remove unused Testnet code in GetMasternodePayment/GetTotalBudget
- We use the same reward structure on both Mainnet and Testnet, this code is not needed
> [Testnet] Fix PoA / Remove Unused Code

- src/main.cpp
- src/main.h
> Chengeset:
> 
> * ~~move ProcessSpork, GetSporkValue, IsSporkActive, ExecuteSpork and mapSporksActive to CSporkManager~~
> * ~~move Sign, CheckSignature, Relay to CSporkMessage~~
> * move ReprocessBlocks out of sporks to main.cpp / rename DisconnectBlocksAndReprocess to DisconnectBlocks
> * ~~rename SporkKey to SporkPubKey~~
> * ~~bugfix: only set strMasterPrivKey if spork signature produced by that key was verified successfully~~
> * ~~few log format changes, cleaned up includes~~
> * ~~Protect CSporkManager with critical section~~
> * ~~bugfix:  do not accept sporks with nTimeSigned way too far into the future~~
> * ~~remove unused sporks: 7, 11, 12~~
> * ~~Refactor code to get rid of repeated if/else blocks (introduce CSporkDef)~~
> 
> Mostly based off of:
> 
> * ~~[Refactor/fix …
> [Trivial] Restore ReprocessBlocks in main.cpp / Rename DisconnectBlocksAndReprocess to DisconnectBlocks

- src/rpc/rawtransaction.cpp
- src/wallet/rpcwallet.cpp
Currently PaymentID is displayed in all raw transactions. Change the behavior to only show if the transaction `IsMine`.
> [Wallet] Only display PaymentID if the transaction IsMine

- src/net.cpp
- src/net.h
> Removing the `RecvLine` unused function in net.cpp.
Simple cleanup from https://github.com/PIVX-Project/PIVX/pull/2133
> [Upstream] [Net] Remove unused RecvLine function.

- src/main.cpp
- src/main.h
- src/masternode.cpp
- src/masternodeman.cpp
- src/miner.cpp
- src/wallet/wallet.cpp
- Remove unused IsKeyImageSpend2
- Rename IsKeyImageSpend1 to IsSpentKeyImage - This better aligns with current IsSpent naming
> [Trivial] Remove IsKeyImageSpend2 / Rename IsKeyImageSpend1 to IsSpentKeyImage

- src/qt/bitcoingui.cpp
As mentioned in the Testnet channel, when you are syncing a node that has received a lot of rewards/transactions while the wallet was closed will get spammed with a large number of notifications. Fix this by checking if we are synced.
> [Qt] Only show notifications when synced to prevent spam

- src/Makefile.test.include
- src/addrman.cpp
- src/addrman.h
> Backport of [bitcoin#6720](https://github.com/bitcoin/bitcoin/pull/6720) and [bitcoin#7212](https://github.com/bitcoin/bitcoin/pull/7212)
> 
> * Adds several unittests for CAddrMan and CAddrInfo.
> * Makes small modifications to CAddrMan to allow deterministic and targeted tests.
> * Increases the accuracy of CAddrMan tests.
> * Removes non-determinism in tests by overriding the random number generator.
> * Extracts testing code from addrman class to test class.
> 
> One more step for #799.
from https://github.com/PIVX-Project/PIVX/pull/902
Another part of getting our tests restored.
We already have the test files, we were missing the updates to addrman to allow deterministic and targeted tests.
> [Upstream] [Tests] Add tests for CAddrMan

- src/zxcvbn/scoring.cpp
Minor update to zxcvbn-cpp, the Password Strength Estimation Library we use to enforce minimum password strength
- Avoid uninitialized error when max(t.second for t in optimal.g[k]) == std::numeric_limits<guesses_t>::max()
from https://thelig.ht/code/zxcvbn-cpp/commit/9520d5628004f2f828a84d11daecfadf368444ca.html
> Update zxcvbn-cpp (Password Strength Estimation Library)

- src/Makefile.am
- src/coins.cpp
- src/coins.h
- src/init.cpp
- src/main.cpp
- src/main.h
- src/memusage.h
- src/test/coins_tests.cpp
- src/txdb.h
> This adds a basic foundation for accurate memory counting (memusage.h, with some implementation-specific assumptions, but at least the tree node and hashtable node implementations used are very generic and straightforward, so likely accurate for several systems). On the tested system at least, they are exact, ignoring memory fragmentation (tested using a single binary creating and modifying large amounts of different configurations of these data structures, and observing total resident set size afterwards). I expect this to be useful for other resource-limiting subsystems later on.
> 
> Then, this is used to implement accurate memory usage counting for CCoins objects, and efficiently computed memory usage counting for CCoinsViewCache (using cached totals, and increments/decrements on …
> [Upstream] [Backport] Implement accurate UTXO cache size accounting

- src/qt/receiverequestdialog.cpp
Fixing an old issue / request
When trying to scan QR codes from the Mobile Wallet/Web Wallet, it wouldn't work correctly as the URI was prepended to it. Remove this to allow easier scanning. Could potentially be an option/setting.
> [Qt] Use Stealth Address instead of URI for Request Payment QR Code by lyricidal

- src/wallet/db.cpp
> Coming from [bitcoin#11017](https://github.com/bitcoin/bitcoin/pull/11017)
> 
> > This PR intends to plug some leaks. It specifically implements adherence to the requirement in BDB to close a handle which failed to open (https://docs.oracle.com/cd/E17276_01/html/api_reference/C/dbopen.html):
> > > The DB->open() method returns a non-zero error value on failure and 0 on success. If DB->open() fails, the DB->close() method
> > > must be called to discard the DB handle.
simple backport from https://github.com/PIVX-Project/PIVX/pull/2197
> [Upstream] [Wallet] Close DB on error

- src/logging.cpp
- src/wallet/db.cpp
A few missed changes for usage of fsbridge for fopen and freopen as we did not have logging.cpp at the time
> Abstracts away how a path is opened to a `FILE*`.
> Reduces the number of places where path is converted to a string
> for anything else but printing.
> backports https://github.com/bitcoin/bitcoin/commit/2a5f574762614b74dee738392057200dd28c64fb
> [Trivial] Add missed updates of fsbridge for fopen and freopen

- src/coins.cpp
> backports [bitcoin#5967](https://github.com/bitcoin/bitcoin/pull/5967)
> 
> > Previously it would break if you flushed a parent cache while there was a child cache referring to it. This change will allow the flushing of parent caches.
> > It also modifies the unit test to include flushing of intermediate caches.
another simple backport from https://github.com/PIVX-Project/PIVX/pull/1774
> [Upstream] [Core] Alter assumptions in CCoinsViewCache::BatchWrite

- src/chainparams.cpp
- src/main.cpp
Block 700k will occur in a few days, push the Hard Fork to block 750k
Increase Ring Sizes from 25-30 to 27-32, keeping our usual range between minimum and maximum
Successfully tested on Testnet (with a tighter range of Ring Sizes 30-32)
> [Consensus] [Hard Fork] Adjust Hard Fork height to Block 750000 / Change Ring Sizes to 27-32

- src/qt/receivecoinsdialog.cpp
Fixing a minor bug introduced by my own code changes without compensating for the adjustments for the smaller screens that display a truncated version of the address. In this case, we change from copying the LineEdit to the actual Master Account, Integrated addresses are not truncated.
> [Qt] Fix address copying on small screens

- src/main.cpp
- src/main.h
- src/qt/optionspage.cpp
- src/qt/sendcoinsdialog.cpp
- src/wallet/wallet.cpp
This fix is related to the Hard Fork/Ring Size bump - the ReVerifyPoS function would cause issue because it was expecting a certain amount of decoys/rings for that block. When the rings change this causes an issue with PoA mining expecting the previous amount of Rings. Fix this by adding 0 as a simple identifier to say that the height should be the current active tip, otherwise use the height passed in.
> [Consensus] PoA fix for after hard fork

- src/qt/forms/optionspage.ui
- src/qt/forms/overviewpage.ui
- src/qt/optionspage.cpp
- src/qt/optionspage.h
- src/qt/overviewpage.cpp
- src/qt/overviewpage.h
Preliminary implementation - adding the` isRuninngQuery` boolean to avoid overexerting CoinGecko's free API. Set to false initially.
Allows for selection of multiple currencies, including:
USD
CAD
EUR
GBP
BTC
ETH
XAU
XAG
Thanks to CoinGecko
https://www.coingecko.com/en/api
> [Qt] Add Alternative Currency Value

- src/chainparams.cpp
- src/chainparams.h
- src/main.cpp
Testnet had different Hard Forks/Ring Sizes than Mainnet - add a specific check for them
This aligns the builds to be usable on each network, as they had slightly deviated from each other due to above
> [Testnet] Add Testnet specific changes

- src/amount.h
- src/wallet/wallet.cpp
Remove `DUST = COIN / 100000` and the 2 checks that use it as they aren't required.
> [Trivial] Remove DUST variable

- src/qt/bip38tooldialog.cpp
- src/qt/bip38tooldialog.h
- src/qt/forms/bip38tooldialog.ui
- src/qt/forms/coincontroldialog.ui
- src/qt/forms/multisenddialog.ui
- src/qt/forms/signverifymessagedialog.ui
> This pulls out some UI refactoring and unrelated additions from #509 so they don't get held back.
> 
> * Standardize the use of QToolButton over QPushButton in instances where the button was being
>   used as a utility button (copy/paste/addressbook) buttons interacting with text inputs.
> * Standardize the CSS styling of all QToolButton elements.
> * Remove nefarious (empty) `placeholderText` properties from `.ui` files.
> * Update strings in BIP38 dialog to match the functionality there.
> * Change from returning Hex to returning WIF private key for decrypted BIP38 key.
> * Update ~~MultiSig~~/MultiSend UI's to use QToolButton
> 
> See individual commit comments for full details.
> 
> ### Rational for using a different button color for Tool Buttons
> Tool buttons are never required to …
> [Upstream] [Qt] Standardize and clean up new UI elements

- src/wallet/rpcwallet.cpp
- src/wallet/wallet.cpp
- src/wallet/wallet.h
When using Send All (sendalltostealthaddress), it would give an incorrect TXID. This should fix that.
> [Fix] Send All - Incorrect Transaction ID

- src/qt/forms/overviewpage.ui
- src/qt/overviewpage.cpp
Need Help? links to https://prcycoin.com/knowledge-base/wallets/sluggish-large-wallet-dat-solution/
> [Qt] Add warning to Overview when wallet is larger than 10k transactions

- src/Makefile.am
- src/Makefile.test.include
- src/crypter.cpp
- src/crypter.h
- src/crypto/aes.cpp
- src/crypto/aes.h
- src/crypto/ctaes/COPYING
- src/crypto/ctaes/README.md
- src/crypto/ctaes/bench.c
- src/crypto/ctaes/ctaes.c
- src/crypto/ctaes/ctaes.h
- src/crypto/ctaes/test.c
- src/test/crypto_tests.cpp
- src/wallet/test/crypto_tests.cpp
> Coming from upstream [7689](https://github.com/bitcoin/bitcoin/pull/7689)
> 
> ```
> slow and simple AES implementation.
> 
> Performance on modern systems should be around 2-10 Mbyte/s (for short to larger messages), which is plenty for the needs of our wallet.
> ```
from https://github.com/PIVX-Project/PIVX/pull/1486
> [Upstream] Replace OpenSSL AES with ctaes-based version

- .github/workflows/prcy-build-factory-debug.yml
- .github/workflows/prcy-build-factory.yml
As per https://github.com/actions/runner-images/issues/6002:
> Deprecation will begin on 8/8/2022 and the image will be fully unsupported by 12/1/2022
Build for Linux remains behind for compatibility as it does not use the `depends` folder - we don't distribute this one anyways.
> [GitHub Actions] Update Ubuntu to 20.04 as 18.04 will be deprecated

- src/wallet/wallet.cpp
- GetPubKey() can be an expensive check and is not necessary to be recalled every staking loop in the context that it is used - move it outside of the loop and use it as a variable.
- We were initializing another CBlockIndex when we could just use chainActive.Height() instead
> [Wallet] Minor CreateCoinStake Cleanup

- src/qt/prcycoin.cpp
This can be useful for PRCY Toolkit users and/or if you use a QT wallet with RPC commands
> [Qt] Add bypasslogin to allow hiding the password box on launch

- configure.ac
Minor fix for configure.ac - the initial check was already commented out, but wasn't removed further down
> [Build] Remove check for unused BOOST_REGEX

- src/compat/byteswap.h
- src/compat/endian.h
- src/crypto/common.h
- src/hash.cpp
- src/main.cpp
- src/net.cpp
- src/primitives/block.cpp
- src/primitives/transaction.h
- src/script/script.h
- src/serialize.h
- src/test/serialize_tests.cpp
- src/txmempool.cpp
> First step in getting our serialization code up to par with upstream. Backports [bitcoin#5510](https://github.com/bitcoin/bitcoin/pull/5510) with only minor adjustments.
> 
> > Fix issue [bitcoin#888](https://github.com/bitcoin/bitcoin/issues/888).
> > This has been structured so that each compatibility change is one commit that touches only one file. After the initial build change, they are independent.
> > Most extensive changes are in 'src/serialize.h: base serialization level endianness neutrality'. I had to replace READDATA and WRITEDATA with functions that take sized integer types to make use of the proper endian.h functions. I'm confident that the end result is the same, although this may require more tests.
> > I've tested this on mipsbe32.
> > All tests pass
> > Testnet syncs …
> [Upstream] [Core] Big endian support

- contrib/prcycoin-qt.pro
- src/Makefile.am
- src/Makefile.test.include
- src/coins.h
- src/hash.h
- src/masternode-budget.h
- src/memusage.h
- src/prevector.h
- src/primitives/transaction.h
- src/qt/transactionrecord.h
- src/rpc/masternode.cpp
- src/script/interpreter.cpp
- src/script/script.cpp
- src/script/script.h
- src/script/sign.cpp
- src/serialize.h
- src/test/miner_tests.cpp
- src/test/prevector_tests.cpp
- src/test/script_P2SH_tests.cpp
- src/test/script_tests.cpp
- src/test/sigopcount_tests.cpp
- src/wallet/walletdb.cpp
> Based on:
> 
> * [x]  [[Core] Big endian support #1554](https://github.com/PIVX-Project/PIVX/pull/1554)
> 
> This introduces `prevector<N, T>`, a new basic data type which is a fully API compatible drop-in replacement for `std::vector<T>` and uses it for the script, to reduce the considerable memory overhead of vectors in cases where they normally contain a small number of small elements.
> 
> Original tests in Bitcoin showed a reduction in dbcache memory usage by **23%**, and made an initial sync **13%** faster.
> 
> Backported from the following upstream's PRs, with only additional edits in the 2nd layer scripts (`masternode-payments`, `masternode-budget`) and in the unit tests (to address the differences in `insecure_rand`):
> 
> * [Add pre-allocated vector type and use it for …
> [Upstream] [Core] Prevector

- src/init.cpp
- src/main.cpp
- src/script/sigcache.cpp
- src/script/sigcache.h
> Coming from [bitcoin#6918](https://github.com/bitcoin/bitcoin/pull/6918) .
> 
> > Changes the -maxsigcachesize argument from entries to megabytes
> > Change the default to 40 MiB (as opposed to ~10 MiB before), corresponding to over 500000 entries on 64-bit systems.
> > Store salted SHA256 hashes in the cache, rather than full entries.
> > Switch implementation from std::set to boost::unordered_set (smaller and faster)
> > Remove cache entries after having been validated inside a block, to keep the cache fresh.
> 
> This is the first step towards an up-to-date sigcache. Next one will be to back port the CuckooCache implementation.
from https://github.com/PIVX-Project/PIVX/pull/1668
> [Upstream] [Backport] Make sigcache faster, more efficient, larger

- contrib/prcycoin-qt.pro
- src/Makefile.am
- src/Makefile.test.include
- src/cuckoocache.h
- src/init.cpp
- src/main.cpp
- src/script/sigcache.cpp
- src/script/sigcache.h
- src/test/cuckoocache_tests.cpp
- src/test/test_prcycoin.cpp
> Built on top of #1668.
> 
> Part of the back port series to get us closer to upstream's sigcache current state.
> 
> The main ones are:
> 
> * [Better SigCache Implementation bitcoin/bitcoin#8895](https://github.com/bitcoin/bitcoin/pull/8895)
> * [De-duplicate SignatureCacheHasher bitcoin/bitcoin#9480](https://github.com/bitcoin/bitcoin/pull/9480)
> * [build: Include cuckoocache header in Makefile bitcoin/bitcoin#9393](https://github.com/bitcoin/bitcoin/pull/9393)
from https://github.com/PIVX-Project/PIVX/pull/1669
> [Upstream] Better sigcache implementation (CuckooCache)

- .github/workflows/prcy-build-factory-debug.yml
- .github/workflows/prcy-build-factory-ubuntu20.yml
- .github/workflows/prcy-build-factory.yml
Jumping to building with Ubuntu 20 too early caused issues on older distros. Go back to Ubuntu 18, while adding a Ubuntu 20 Workflow that is disabled by default, but can be run with `[focal]` in the commit
> [GitHub Actions] Use Ubuntu 18 for Releases / Add Separate Ubuntu 20 Workflow 

- src/net.cpp
> Value can be significantly higher if the users uses addnode.
> 
> Coming from upstream#[8944](https://github.com/bitcoin/bitcoin/pull/8944)
from https://github.com/PIVX-Project/PIVX/pull/1769
> [Upstream] [Net] Remove bogus assert on number of oubound connections.

- src/addrman.h
- src/main.cpp
- src/net.cpp
- src/net.h
> Running 4.2 branch with `enable-debug`. Fixing:
> 
> ```
> POTENTIAL DEADLOCK DETECTED
> Previous lock order was:
> pnode->cs_vRecvMsg net.cpp:1830 (TRY) (in thread )
> (1) cs_main main.cpp:5275 (in thread )
> (2) cs_vSend net.cpp:2465 (in thread )
> Current lock order is:
> (2) pnode->cs_vSend net.cpp:1846 (TRY) (in thread )
> (1) cs_main main.cpp:6018 (TRY) (in thread )
> ```
> 
> Plus, added few more minor possible races fixes too.
> 
> Back porting: [bitcoin#8862](https://github.com/bitcoin/bitcoin/pull/8862) [bitcoin#9225](https://github.com/bitcoin/bitcoin/pull/9225) [bitcoin#9535](https://github.com/bitcoin/bitcoin/pull/9535)
from https://github.com/PIVX-Project/PIVX/pull/1780
> [Upstream] [Net] cs_vSend-cs_main deadlock detection fixed.

- src/net.cpp
> Backports [bitcoin#9008](https://github.com/bitcoin/bitcoin/pull/9008).
> 
> > nMaxInbound might very well be 0 or -1, if the user prefers to keep a small number of maxconnections.
> > Note: nMaxInbound of -1 means that the user set maxconnections
> > to 8 or less, but we still want to keep an additional slot for
> > the feeler connection.
> 
> Have faced this assertion crash few times in testnet already.
from https://github.com/PIVX-Project/PIVX/pull/2682
> [Upstream] [net] Remove assert(nMaxInbound > 0) 

- src/chainparams.cpp
- src/chainparams.h
- src/wallet/wallet.cpp
This makes it easier to add, change prefixes vs using hard numbers
> [ChainParams] Move Stealth and Integrated Address Prefixes to ChainParams

- src/qt/sendcoinsdialog.cpp
- src/wallet/rpcwallet.cpp
- src/wallet/wallet.cpp
- src/wallet/wallet.h
SendAll was not taking into account Masternodes that were collateralized so we add it as a parameter when attempting to send all.
`default=false`
`sendalltostealthaddress ADDRESS` [false] - does not include MNs to be sent
`sendalltostealthaddress ADDRESS true` includes ALL coins, locked or not
> Add parameter to sendalltostealthaddress to include locked coins or not

- src/qt/historypage.cpp
- Remove unreachable code on History tab
- We can't get the transactions with the wallet unlocked
- There is a return above this code when the wallet is locked preventing ever reaching the code (which doesn't work anyway)
- On further inspection, part of this was also a copy of the Overview screen's Recent Transactions code that didn't belong here 
- Return immediately if wallet doesn't exist/is locked in updateTableData
- No point to check TRY_LOCK for a function that won't work without an unlocked wallet
- Fix Date/Amount/Address search on History page
- Incorrect QDateTime::fromString format was being used and so the date was invalid (Date selection was being compared to nothing)
- Due to the above, the `hide` boolean was also not being used correctly for other searches as it would …
> [Qt] History Tab Cleanup

- src/rpc/budget.cpp
- src/rpc/masternode.cpp
- src/wallet/rpcwallet.cpp
Unify IsLocked() checks to EnsureWalletIsUnlocked() in some functions that were missed
This ensures that the same check/error message is used/returned
> [RPC] Unify IsLocked() checks to EnsureWalletIsUnlocked() in some functions that were missed

- configure.ac
- doc/dependencies.md
- src/fs.cpp
- src/init.cpp
- src/qt/guiutil.cpp
- src/rpc/protocol.cpp
- src/scheduler.cpp
- src/test/scheduler_tests.cpp
- src/torcontrol.cpp
- src/util.cpp
- src/utiltime.cpp
> The configure script has been updated to require a detected version of at least 1.57.0, and now-redundant sub-checks have been removed. Precompiler macros that offered version or feature fallbacks have also been largely removed as they are unnecessary.
> 
> Finally, this also updates some Boost Filesystem Path codebase that was using deprecated methods, and sets the `BOOST_FILESYSTEM_NO_DEPRECATED` macro so that such methods do not get re-added to the codebase in the future.
from https://github.com/PIVX-Project/PIVX/pull/1703
> [Upstream] [Build] Require minimum boost version 1.57.0

- src/init.cpp
Fixes this error on init when running with -disablewallet
```
************************
EXCEPTION: St13runtime_error       
CDB : Error 2, can't open database wallet.dat       
prcycoin in AppInit()
```
> [Wallet] Fix runtime_error with -disablewallet

- src/qt/bitcoingui.cpp
> When running the client with the `-disablewallet` option, the staking icons should always be hidden. This adds a check to see if `walletFrame` has been set before showing/updating the icons.
from https://github.com/PIVX-Project/PIVX/pull/781
> [Qt] Don't show staking status icons without a wallet

- src/qt/bitcoingui.cpp
Minor follow up to #290 
When running the client with the `-disablewallet` option, found a number of items that were overlaying the menu bar
> [Qt] Fix UI when wallet is disabled

- src/prevector.h
> Two simple additions to `prevector` class:
> 
> * name the union, to prevent compiler warnings emitted by clang (from [Name union to prevent compiler warning bitcoin/bitcoin#7146](https://github.com/bitcoin/bitcoin/pull/7146))
> * use non-static data member initializers for `_size` and `_union` (from [refactor: Lift prevector default vals to the member declaration bitcoin/bitcoin#14266](https://github.com/bitcoin/bitcoin/pull/14266))
from https://github.com/PIVX-Project/PIVX/pull/1634
> [Upstream] [Core] prevector: named union and defaults vars initialization

- doc/Doxyfile.in
> Pre-process source files by searching for comment strings containing `TODO` or `FIXME` and replacing with the doxygen `\todo` flag.
> 
> This is an internal conversion only, and won't change the source view of affected files.
from https://github.com/PIVX-Project/PIVX/pull/1051
Doxygen now hosted at: https://doxygen.prcycoin.com
> [Upstream] [Doxygen] Generate Todo list

- src/init.cpp
- src/wallet/db.cpp
- src/wallet/db.h
- src/wallet/walletdb.cpp
- src/wallet/walletdb.h
> Quick back ports, coming from [bitcoin#5983](https://github.com/bitcoin/bitcoin/pull/5983) and [bitcoin#9227](https://github.com/bitcoin/bitcoin/pull/9227).
from https://github.com/PIVX-Project/PIVX/pull/1802
> [Upstream] [Wallet] Make nWalletDBUpdated atomic to avoid a potential race

- src/qt/clientmodel.cpp
- src/qt/clientmodel.h
- src/qt/rpcconsole.cpp
> The masternodes polling was starting when the clientModel object is generated, locking `cs_main` every certain amount of time without care on whether the information is being presented or not. This PR changes it, the polling timer will only be started when the information is needed on the screen and stopped when the user leaves such screen.
from https://github.com/PIVX-Project/PIVX/pull/1782
> [Upstream] [GUI] Start masternodes polling timer only when is needed.

- src/wallet/wallet.cpp
- src/wallet/wallet.h
This variable isn't really needed, minor cleanup to remove it in preparation for further refactoring of AvailableCoins/MintableCoins/SelectStakeCoins functions in upcoming PR(s).
> [Wallet] Remove cannotSpend variable from AvailableCoins

- depends/packages/miniupnpc.mk
- depends/patches/miniupnpc/dont_leak_info.patch
- doc/dependencies.md
> Coming from [bitcoin#20421](https://github.com/bitcoin/bitcoin/pull/20421)
> 
> Creating the dll subdir is no-longer required. We can also drop our wingen patch.
from https://github.com/PIVX-Project/PIVX/pull/2329
> [Upstream] [Depends] Bump miniupnpc to 2.2.2

- depends/packages/qt.mk
- depends/patches/qt/fix_mingw_cross_compile.patch
- depends/patches/qt/mac-qmake.conf
> Follow up on removing sed usage in https://github.com/bitcoin/bitcoin/pull/19761. Also nice to revisit & cleanup before 5.15.x.
from https://github.com/bitcoin/bitcoin/pull/19867
Follow up to https://github.com/PRCYCoin/PRCYCoin/pull/303
> [Upstream] build: document and cleanup Qt hacks

- src/main.cpp
- src/net.cpp
- src/net.h
This fixes the following errors that were showing up in the debug.log since #249:
```
ProcessMessage(version, 100 bytes) FAILED peer=1
ProcessMessage(verack, 0 bytes) FAILED peer=1
ProcessMessage(ping, 8 bytes) FAILED peer=1
ProcessMessage(addr, 31 bytes) FAILED peer=1
ProcessMessage(inv, 37 bytes) FAILED peer=1
```
The cause was returning false immediately if CNodeState* state was NULL. This was causing the Qt Wallet to be blocked attempting to Process Messages from peers until there was a state. This was only added for our IsUnsupportedVersion function that we use to block older versions, but can be done with a better approach: Rename and edit our IsUnsupportedVersion to align with DisconnectOldProtocol.
> [Net] [Cleanup] Fix ProcessMessage(s) / Edit IsUnsupportedVersion to DisconnectOldVersion

- src/qt/optionspage.cpp
Sometimes you just want to enable Staking without consolidation. Previously you would have to use the Debug Console / disable consolidation, so add an Ignore button to the Qt dialog box to do so.
> [Qt] Add "Ignore" button for Consolidation upon Enabling Staking

- .github/workflows/prcy-build-factory-debug.yml
- .github/workflows/prcy-build-factory-ubuntu20.yml
- .github/workflows/prcy-build-factory.yml
Solving the following in our GitHub Actions Workflows: 
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2
> [GitHub Actions] Update actions/checkout to v3

- src/init.cpp
- src/qt/prcycoin.cpp
Deep rabbit-hole this one took us on, but this looks to be the cause of the infamous
`GUI: QObject::~QObject: Timers cannot be stopped from another thread`
Hopefully this one can finally be laid to rest.
> [Qt] [Fix] Remove registerNodeSignal / requestedRegisterNodeSignal

- src/qt/forms/optionspage.ui
- src/qt/optionspage.cpp
- src/qt/optionspage.h
- src/qt/sendcoinsdialog.cpp
Similar to 2FA before, offer a setting to "Request passphrase before sending any transactions" - they can be used together.
> [Qt] "Request passphrase before sending any transactions" setting

- src/wallet/wallet.cpp
AvailableCoins was not checking for inSpendQueueOutpoints, this fixes that
> [Wallet] Restore inSpendQueueOutpoints to AvailableCoins

- src/masternode.cpp
- src/masternode.h
> In `CalculateScore`, `GetMasternodeInputAge` and `GetBlockHash` we had `chainActive` accessed without cs_main being held. This PR fixes it. No functional changes. Can be added to 4.2.1 back ports list as well.
from https://github.com/PIVX-Project/PIVX/pull/1791
> [Upstream] [Masternodes] Missing cs main locks in CalculateScore and GetMasternodeInputAge

- src/main.cpp
- src/main.h
- src/masternode-budget.cpp
- src/masternode-payments.cpp
- src/masternodeman.cpp
> In several places we had synchronized data structures accessed without cs_main being held.
from https://github.com/PIVX-Project/PIVX/pull/1785
More clean up around missing LOCKs
> [Upstream] lock cs_main for Misbehaving

- src/main.cpp
These were incorrectly removed at some point. Restoring them, as per the comment above it:
> // Resend wallet transactions that haven't gotten in a block yet
> // Except during reindex, **_importing and IBD_**, when old wallet
> // transactions become unconfirmed and spams other nodes.
> [Net] Restore check for Importing/IBD on resend wallet transactions

- src/main.cpp
- src/main.h
- src/miner.cpp
- src/txmempool.cpp
> Coming from btc@c8b92486c4eca1287546b0683b6af3551db1fe67
Cherry-pick from https://github.com/PIVX-Project/PIVX/pull/1631 (leaving out the first commit as we do not have zerocoin)
> [Upstream] Remove obsolete reference to CValidationState from UpdateCoins.

- src/kernel.cpp
- src/kernel.h
- src/main.cpp
cherry-picked from https://github.com/PIVX-Project/PIVX/pull/925
Two checks on the age of a transaction used to stake were removed by mistake in https://github.com/PRCYCoin/PRCYCoin/pull/320/commits/177429130261ce2cb79a06dfc90dda3ac565056c. We reintroduce them here.
> [Upstream] [Consensus] Time checks

- src/chainparams.cpp
- src/chainparams.h
- src/kernel.cpp
- src/main.cpp
- src/main.h
- src/wallet/wallet.cpp
> There is a bug occurring sometimes on regtest where a block is not accepted due to `CheckStakeKernelHash() : min age violation`. This is because the min age requirement for RegTest was changed (in #812) inside `Stake` but not in `CheckProofOfStake` (the error indicates also the wrong function).
> 
> This fixes it and moves `nStakeMinAge` to chain params (instead of having it as rogue external variable) and sets it to `0` for RegTest (for consistency). Also fixes the error messages in kernel.cpp.
from https://github.com/PIVX-Project/PIVX/pull/976
> [Upstream] [Refactor] Fix stake age checks for regtest

- src/wallet/wallet.cpp
Simple backport 
> Fixes #728 
Thanks to @licobc for catching it.
from https://github.com/PIVX-Project/PIVX/pull/734
> [Staking] Ensure nCredit is correctly initialized in CreateCoinStake

- src/wallet/wallet.cpp
Simple fix, was using a differently named variable so we didn't get the correct message and just got "Not enough spendable balance!" instead.
> [Wallet] Fix incorrect error messages on Send

- src/miner.cpp
- src/miner.h
- src/rpc/mining.cpp
> ### **Release notes**
> * [Mining] Unnecessary mining threads now exit after PoS has begun
> * [Staking] The staking thread dormancy is more efficient during PoW
> * [Performance] Some unnecessary processing in the mining thread removed
> * [RPC] setgenerate errors if attempted to turn on after end of PoW
> * [Build] Wallet only routines conditionalized in miner.h
> * [Refactoring] Log messages with bitcoin named routines changed for easier rename of routines in the future.
> 
> In order to better explain the changes in this PR, a review of the existing code would be helpful.
> 
> ### **Backstory**
> When fixing a PIVX forked coin's transition from PoW to PoS, it was observed that mining threads go into tight infinite loops after the switch to proof of stake. This can be seen with a …
> [Upstream] [Staking] Modify miner and staking thread for efficency

- src/qt/trafficgraphwidget.cpp
> Qt 5.15 no longer implicitly includes QPainterPath, so explicitly
> include it here.
from https://github.com/PIVX-Project/PIVX/pull/1683
Simple backport/fix. Testing and compiling with Qt5.15 on macOS today and ran into this.
> [Upstream] [GUI] Add missing QPainterPath include

- src/rpc/rawtransaction.cpp
- src/wallet/wallet.cpp
More from compiling on macOS, turning on `-Wthread-safety-analysis` shows a number of compiler warnings with c++11 for acquiring mutexes that are already held.
This cleans up those warnings.
`wallet/wallet.cpp:6273:21: warning: acquiring mutex 'cs_wallet' that is already held [-Wthread-safety-analysis]
LOCK(cs_wallet);`
`rpc/rawtransaction.cpp:98:21: warning: acquiring mutex 'pwalletMain->cs_wallet' that is already held [-Wthread-safety-analysis]
LOCK(pwalletMain->cs_wallet);`
> [Cleanup] Thread-safety-analysis warnings

- src/Makefile.am
This was causing compile issues on Ubuntu 16 to create the AppImage (AppImage should be created on a lower OS to support more OSs).
Might also fix RISCV64 Qt compile, as it was failing with a similar error -> it does. https://github.com/PRCYCoin/PRCYCoin/actions/runs/3926350006/jobs/6712007359
> [Build] Fix missing zxcvbn PIE_FLAGS

- .github/workflows/prcy-build-factory.yml
After the fix in #335, we can now re-enable Qt builds for riscv64-linux-gnu
> [Build] Re-enable Qt for riscv64-linux-gnu

- src/rpc/client.cpp
- src/wallet/rpcwallet.cpp
This extends the `sendtostealthaddress` RPC command to allow locking outputs.
Examples below:
`sendtostealthaddress ADDRESS amount` -> does as expected, no changes required
`sendtostealthaddress ADDRESS amount false` -> same as above, false/do nothing
`sendtostealthaddress ADDRESS amount true` -> true implies lock that particular output
Can be useful for creating a Staker or Masternode(s) (`createmasternode` would be more useful in that case as it is more of an all-in-one)
> [RPC] Extend `sendtostealthaddress` to allow locking outputs

- src/qt/forms/overviewpage.ui
- src/qt/overviewpage.cpp
Previous iteration did not correctly set the link, fix that and use less variables
> [Qt] Fix broken link for large wallet warning

- src/wallet/wallet.cpp
> Problem:
> 
> Essentially, every time that the controller started a masternode, it was looping over the entire set of transactions and outputs to get the available ones, then looping again for the specific collateral utxo of the masternode that needs to be started. so.. if the wallet had a big number of transactions, the start all had to process an excessive amount of utxo for each masternode being started Making the start all command slow as hell.
> 
> Solution:
> 
> `GetMasternodeVinAndKeys` method rewritten to directly find the collateral utxo in the wallet's map, perform the availability validations and return the needed keys. Zero loops.
from https://github.com/PIVX-Project/PIVX/pull/1698
> [Upstream] [Wallet] Masternodes start performance boost

- src/masternode.cpp
- src/wallet/wallet.cpp
- src/wallet/wallet.h
> Built on top of #1719 .
> 
> Fixing/Improving a bad error notification string showed in the GUI due the `CMasternodeBroadcast::Create` calling `CWallet::GetMasternodeVinAndKeys` and returning to the GUI the same string error output that is being printed to the log (with all of the extra data, including function names, service etc..).
> 
> Can be easily tested creating a masternode, then not waiting for the 15 confirmations and trying to start the node via the menu single masternode start (click on the masternode row and then press start). Without the last commit, will popup a bad error notification text.
from https://github.com/PIVX-Project/PIVX/pull/1732
> [Upstream] [GUI] Better start single MN error description. 

- src/activemasternode.cpp
- src/masternode.cpp
> Removed a not needed balance check in `CActiveMasternode::ManageStatus` (the remote masternode doesn't need to have balance), plus added better logging for the `notCapableReason`.
> 
> long talk with zebra about this ☕ , will need further cleanup but this is going for the right track.
from https://github.com/PIVX-Project/PIVX/pull/1834
> [Upstream] CActiveMasternode::ManageStatus remove unneeded GetBalance check

- src/wallet/wallet.cpp
Example: 
```
2023-01-25 20:04:44 Making RingCT using ring size=30
2023-01-25 20:04:44 Selecting coinbase decoys for transaction
2023-01-25 20:04:44 Selected transaction: 023ea12ec467192cb329a762a896c5b174ed61bfd0931e50c00caf42426e2a07 is not in the main chain
```
> [Wallet] Better logging for when selected transaction is not in main chain

- src/init.cpp
- src/wallet/wallet.cpp
Fixes:
```
wallet/wallet.cpp:5655:5: warning: expression result unused [-Wunused-value]
fCombineDust;
^~~~~~~~~~~~
```
A unique, and super annoying, case where even when you set `combinedust=false` in prcycoin.conf your UTXOs would still get consolidated, wasting the time spent to split the UTXOs in the first place.
> Fix unused-value warning for fCombineDust

- src/qt/forms/optionspage.ui
- src/qt/optionspage.cpp
Brought to our attention by a user on Telegram, fee text was leftover from forking the code.
> [Qt] Fix incorrect fees displayed for new deposits on Options page

- src/wallet/wallet.cpp
This ensures that Masternode Collateral/below Minimum Stake amount UTXOs are not selected for Staking/considered as Mintable Coins
Essentially, duplicated code in AvailableCoins that eventually gets cleaned up better moving into the next larger PRs/Hard Fork.
> [Wallet] MintableCoins/SelectStakeCoin Fixes

- src/qt/bitcoingui.cpp
- src/qt/overviewpage.cpp
This fixes the incorrectly displayed Staking Status in Qt after the changes to the Staking flow. Will be re-adjusted when CStakerStatus is introduced from Upstream.
> [Qt] Fix incorrect Staking Status

- src/rpc/server.cpp
- src/rpc/server.h
- src/wallet/rpcwallet.cpp
- src/wallet/wallet.cpp
RPC command to erase a transaction from the wallet.
Usage: `erasefromwallet TXID`
Result: Done or Invalid or non-wallet transaction id (if the TXID does not exist)
In debug.log, a line will be added `Erased wtx TXID from wallet`
Works well with #352 -> Transactions that are logged there can be erased to get past the error.
> [RPC] Add `erasefromwallet`

- src/qt/forms/revealtxdialog.ui
- src/qt/revealtxdialog.cpp
- src/qt/revealtxdialog.h
Button location:
Confirm dialog:
Success dialog:
Potential Masternode dialog:
Preliminary UI version of deleting transactions. With option to hide success dialog to speed up the process (which sets a value for `fHideDeleteSuccess` of true or false - default is true). Checks for a "Potential Masternode Collateral" transaction by the value. Further additions/updates to follow.
Keyboard shortcuts on the TX Dialog screen
Delete/Backspace - will initiate the process.:
Enter -> Accept
Esc -> Reject
> [Qt] Add "Delete Transaction" button on TX Dialog

- src/init.cpp
- src/logging.cpp
- src/logging.h
- src/main.cpp
- src/rpc/server.cpp
- src/rpc/server.h
- src/wallet/db.cpp
- src/wallet/db.h
- src/wallet/rpcwallet.cpp
- src/wallet/wallet.cpp
- src/wallet/wallet.h
- src/wallet/walletdb.cpp
- src/wallet/walletdb.h
First implementation of `DeleteWalletTransactions`, based on the work by @CryptoForge in https://github.com/PirateNetwork/pirate/pull/5 (+ some additional commits surrounding the code from https://github.com/PirateNetwork/pirate/pull/14 & https://github.com/PirateNetwork/pirate/pull/20)
Modified for our code, also adding an RPC command `erasewallettransactions` to run the function on demand.
Otherwise, it will run on a PoA block for now (which makes it run in an approximately hourly interval). Open to different ideas about the intervals/defaults.
Added:
```
-deletetx - "Enable Old Transaction Deletion"
-deleteinterval - "Delete transaction every <n> blocks during inital block download"
-keeptxnum - "Keep the last <n> transactions"
-keeptxfornblocks - "Keep transactions for at least <n> …
```
> [Wallet] Add functionality to delete wallet transactions

- src/Makefile.am
> This adds extra paths that were left out and ensures that `.gcda` and `.gcno` files are properly cleaned up.
> 
> Simple way to test this is to run the following chain of commands both without and with the changeset:
> 
> ```
> ./configure --enable-lcov
> make
> make clean && make distclean
> find . -name "*.gcno"
> ```
> 
> Without this, there are leftover (non-cleaned) `.gcno` files, which could cause errors due to stale or fragmented/incomplete information when attempting to generate the coverage report (`make cov`). With this change, the `find` command shows that no such `.gcno` files remain after cleaning.
> 
> This all requires that `lcov` is available on the system, as `configure` will properly error out when using the `--enable-lcov` option if it isn't found.
from …
> [Upstream] [Build] Clean all coverage files during make clean

- src/net.cpp
Since the version block is already in place, no need to check for the heights here.
> Remove Height for Version Block

- src/chainparams.cpp
Add checkpoints at the Hard Fork block and the first few 1000 blocks after it to keep people on the right chain.
> Add Checkpoints after Hard Fork
