PRCYCoin/PRCYCoin

src/qt/optionspage.cpp
This better explains the condition being checked
=> Update Enable Staking MsgBox

src/init.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
Improvements to Staking/Consolidation settings
Combined effort with @lopeed
=> Staking Settings Changes

src/chainparams.cpp, src/chainparams.h, src/poa.cpp
- Add SoftFork block at 120k
new difficulty:
`unsigned int N_BITS_SF = 0x1e127ff8;`
=> Add SoftFork block at 120k

src/poa.cpp
Fixing syncing and allowing PoA to be mined again
Follow up PR to make further adjustments to PoA
=> PoA/Sync Fix

src/chainparams.cpp, src/chainparams.h, src/net.cpp, src/poa.cpp
- Ban v1.0.0.4
- Add PoAFixTime()
- Set PoA Fix time for Friday, March 26, 2021 12:00:00 AM (GMT)
=> Final Updates for v1.0.0.6

src/chainparams.cpp, src/chainparams.h, src/miner.cpp, src/poa.cpp, src/poa.h
- Adding PoA padding
- Updated copyrights
=> Merge Develop > Master for Release

src/chainparams.cpp, src/chainparams.h, src/miner.cpp, src/poa.cpp, src/poa.h
Minor update for re-release
- Remove timed ban/PoA fix
- Additional checkpoints for first PoA after fork
- Sync fix
=> Merge Develop to Master [v1.0.0.6-HotFix]

src/chainparams.cpp
Add 4 more seed nodes/VPS for better connectivity
=> Add More Seed Nodes

src/qt/bitcoingui.cpp, src/qt/bitcoingui.h
- Restore Reddit and Discord links
- Add shortcut for Settings (ALT + 6) (CTRL + 6 on Mac) 
- Fix Blockchain typo
- Add Bridge to Menus
=> [QT] Minor GUI Updates

src/wallet/db.cpp
> Fixes linking problem as seen on GA CMake-macOS [here](https://github.com/PIVX-Project/PIVX/runs/2032160204).
> From [bitcoin#8626](https://github.com/bitcoin/bitcoin/pull/8626)
from https://github.com/PIVX-Project/PIVX/pull/2232
=> [Upstream] [Wallet] Berkeley DB v6 compatibility fix

src/allocators.h
> Straightforward cherry-pick from [bitcoin#10965](https://github.com/bitcoin/bitcoin/pull/10965)
from https://github.com/PIVX-Project/PIVX/pull/2376
=> [Upstream] Replace deprecated throw() with noexcept specifier (C++11)

src/init.cpp, src/main.cpp, src/main.h, src/rpc/server.h, src/test/sighash_tests.cpp, src/test/transaction_tests.cpp, src/wallet/rpcdump.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp
- Remove commented out Team Rewards code
- Remove unused Zerocoin functions
- Remove unused fzcActive boolean
- Remove ReindexAccumulators
- Add EnsureWallet() (Ensure there is a Wallet - removing duplicate code)
=> [Cleanup] Minor Code Cleanup

src/rpc/blockchain.cpp, src/rpc/server.cpp, src/rpc/server.h
- Add getmaxsupply command
Returns the max supply as per the chainparams
=> [RPC] Add getmaxsupply command

src/miner.cpp
Provide info in the debug.log when "PoA Padding Is Reached" or not
=> [Logging] Change PoA Logging

src/wallet/rpcwallet.cpp
Fixing the walletlock RPC command
=> [RPC] Fix walletlock Command

src/chainparams.cpp, src/chainparams.h, src/miner.cpp
Add PoAPadding to chainparams
This will allow for easier access/use in future changes
=> [PoA] Add PoAPadding to chainparams

src/main.cpp
- Fix for AcceptToMemoryPool banning while syncing
Vary the ban score based on whether we are synced or not
=> [Fix] Fix for AcceptToMemoryPool banning while syncing

.github/workflows/prcy-build-factory.yml
=> [Build] Enable UPNP by Default

src/poa.cpp
Add sync fix for block 311332
Add orphan PoS blocks to IsWrongAudit
Add fixed PoS blocks to IsFixedAudit
Add comments
=> [Fix] Syncing and PoA Mining

src/Makefile.qt.include, src/qt/forms/optionspage.ui, src/qt/optionsmodel.cpp, src/qt/optionspage.cpp, src/qt/optionspage.h, src/qt/prcycoin.qrc, src/qt/res/css/WebWallet.css
Add the Web Wallet Theme as an Option
Settings -> Toggle Dark -> Web
Note: Web Wallet Theme might need some updates
=> [UI] Add WebWallet Theme

src/chainparams.cpp, src/chainparams.h, src/main.cpp, src/miner.cpp, src/poa.cpp, src/poa.h
**- Add HardFork at block 350000**
- Add PoA padding (controlled by Consensus)
- Add halving for PoA rewards
- Fix for first PoA block of testnet
- Add reasons for PoA block rejection
- Remove check for padding from CreateNewPoABlock
=> [Fix] PoA Padding/Additional Updates

src/main.cpp, src/net.cpp, src/net.h, src/poa.cpp, src/poa.h
- Modify IsUnsupportedVersion to accept block height
- Modify IsFixedAudit/IsWrongAudit to accept block height
This allows us to use block heights vs the Time-based way we were doing it before
=> Add block height to functions (IsUnsupportedVersion/IsFixedAudit/IsWrongAudit)

src/chainparams.cpp
10 on Main network
5 on Test network
=> Change PoA Padding

src/miner.cpp, src/net.cpp, src/poa.cpp
Once the hard fork has passed, these checks are no longer required
=> [Cleanup] Remove checks for HardFork

src/main.cpp
Previously this was an In-Wallet check only, now adding a Consensus check
=> [Consensus] Enforce MINIMUM_STAKE_AMOUNT

src/chainparams.cpp, src/chainparams.h, src/main.cpp, src/qt/optionspage.cpp, src/qt/walletmodel.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
After https://github.com/PRCYCoin/PRCYCoin/pull/86 the Minimum Staking Amount is enforced via Consensus. Add it to the chainaparams.
=> [Move-Only] Move MINIMUM_STAKE_AMOUNT to chainparams

src/main.cpp, src/main.h, src/masternode-budget.cpp, src/masternode-payments.cpp, src/miner.cpp, src/qt/blockexplorer.cpp, src/rpc/masternode.cpp, src/wallet/wallet.cpp
Based on this commit from PIVX https://github.com/PIVX-Project/PIVX/pull/1848: https://github.com/PIVX-Project/PIVX/pull/1848/commits/288953dad25b7aafef86f730ed1827a5d6de218d
- Modifies GetBlockValue to accept the int nHeight vs const CBlockIndex* ptip
- Removes PoSBlockReward as a function, implementing it into GetBlockValue based on height
- Removes unused variables related to PoSBlockReward
=> [Refactor] Cleaner GetBlockValue implementation

.github/workflows/prcy-build-factory.yml, .travis.yml, contrib/gitian-descriptors/gitian-win.yml, depends/README.md, doc/build-windows.md, doc/release-process.md
> Coming from [btc@15939](https://github.com/bitcoin/bitcoin/pull/15939).
> 
from https://github.com/PIVX-Project/PIVX/pull/1324
=> [Build] Remove Windows 32 bit build.

src/qt/bitcoingui.cpp, src/qt/bitcoingui.h, src/qt/guiutil.cpp, src/qt/guiutil.h, src/qt/rpcconsole.cpp, src/qt/rpcconsole.h
Add Show Qt Folder menu item
Shortcut F3
=> [Qt] Add Qt Directory location

src/chainparams.cpp
Add checkpoint for blocks 369757 and 370034 to fix syncing
=> [Checkpoints] Add checkpoints to fix sync

src/main.cpp
> ## Refactor ConnectBlock() to segregate state tracking items from the 'Just Check' section.
> * Remove a `WriteBlockIndex` that was in the middle of `ConnectBlock()`. This really shouldn't be in this code at all because the index is written by adding it to a list of dirty. This is very likely what has caused PIVX to especially likely to corrupt on force close.
> * Remove the auto-repair db code on init. This seems to actually cause more problems than it fixes.
> * Do not write serials as spent until after the 'Just Check' section. Hold them in a vector until the just check section has passed.
> * Do not write the accumulator checkpoints until the 'Just Check' section has passed.
> * Refactor aspects of the zerocoin checks to be within their own functions external to `ConnectBlock()`. …
=> [Upstream] [Core] Refactor ConnectBlock() to segregate state tracking items [Missed Parts]

.travis.yml, doc/release-process.md, share/genbuild.sh, src/main.cpp, src/masternodeconfig.cpp, src/wallet/wallet.cpp
Bunched a few smaller Upstream PRs/Commits - keeping in line with catching up to latest code.
[Travis] Add separate job to check doc/logprint/subtree https://github.com/PRCYCoin/PRCYCoin/commit/5f76f3649b937840aa134a90cd33525b9d50d740 - https://github.com/PIVX-Project/PIVX/pull/639
Missed include change from PIVX-Project/PIVX@9837f53 https://github.com/PRCYCoin/PRCYCoin/commit/c9d34ec9254939ed52c016d3a8d430f01779b997
[Doc] Change aarch assert sign output folder https://github.com/PRCYCoin/PRCYCoin/commit/53cf2a4a238f9cd6d847edc190f9e5e412f6b9dc  - https://github.com/PIVX-Project/PIVX/pull/585
Not from Upstream, but Trivial nonetheless:
Minor log updates https://github.com/PRCYCoin/PRCYCoin/commit/5e83a5e6030cf8342bc486d60987488faa008bca
Restore commit suffix to version …
=> [Trivial] Minor updates

src/qt/historypage.cpp
This isn't the cleanest fix, but works for the purpose. Can be revisited in future.
(The whole History screen needs a cleanup)
=> [Qt] Fix "All Types" Dropdown on History tab

src/qt/bitcoingui.cpp, src/qt/bitcoingui.h
Add Check For Updates at startup
(still checks [version.txt](https://github.com/PRCYCoin/PRCYCoin/blob/master/version.txt) in the root of this repo)
=> [Qt] Add Check For Updates at Startup

src/chainparams.cpp
Some people were getting stuck reconsidering this block, checkpoint it
=> [Checkpoints] Add checkpoint for block 385916 (PoA)

src/qt/bitcoingui.cpp
Add logging to see what Check For Updates is doing (Plus verify it is running correctly at launch)
=> [Qt] Add logging for Check For Updates

.github/workflows/prcy-build-factory-debug.yml
Compile all builds with DDEBUG_LOCKORDER when "[debug]" is added to the commit message
=> [GitHub Actions] Add DDEBUG_LOCKORDER build to Actions

src/Makefile.am, src/guiinterfaceutil.h, src/init.cpp, src/init.h, src/test/test_prcycoin.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
> This PR does two things:
> 
> 1. Move the `pwalletMain` object inside the `wallet.h` file.
> 2. Move the wallet's parameters initialization to an static method `ParameterInteraction` in the wallet class.
> 
> This is coming (partially) from upstream 25340b7 .
from https://github.com/PIVX-Project/PIVX/pull/1445
=> [Upstream] [Refactor] Init wallet parameters interaction

src/qt/forms/entermnemonics.ui, src/qt/forms/importorcreate.ui, src/qt/forms/intro.ui, src/qt/forms/sendcoinsentry.ui
Trivial, but Update "PRCY Wallet' to "PRCY Coin Wallet"
=> [Trivial] [Qt] Update "PRCY Wallet' to "PRCY Coin Wallet"

src/qt/intro.cpp
> This introduces per-network required disk space into the intro UI in the least intrusive way for now. Mainnet and Testnet have their own static const variables, whereas Regtest is always set to "0"
> 
> <del>This is intended as a temporary fix for #2618,</del> with future intention on moving these over to chainparams a la upstream and using a node IPC interface layer, which we do not have yet.
> 
> Can be tested by passing <del>`-choosedatadir` with a combination of</del> `-testnet`, `-regtest`, or standalone, and this has zero impact on translation strings.
from https://github.com/PIVX-Project/PIVX/pull/2621
Quote adjusted as we don't have choosedatadir yet
=> [Upstream] [GUI] Show disk space requirement per-network

src/qt/forms/optionspage.ui, src/qt/optionspage.cpp
These might be used with or without staking
=> [Qt] Remove "for Staking" from Privacy Settings

src/qt/sendcoinsdialog.cpp, src/wallet/wallet.cpp
Remove Minimum 5 Send from Wallet
=> [Wallet] Remove Minimum 5 Send

src/qt/forms/revealtxdialog.ui, src/qt/historypage.cpp, src/qt/revealtxdialog.cpp, src/qt/revealtxdialog.h
- Add Ring Size to revealtxdialog Dialog
=> [Qt] Add Ring Size to revealtxdialog Dialog

src/qt/forms/historypage.ui, src/qt/historypage.cpp
During recent testnet I was trying to observe the "Payments to yourself" but realized we didn't have - add it
=> [Qt] Add "Payment to yourself" to History dropdown

src/qt/forms/revealtxdialog.ui, src/qt/revealtxdialog.cpp, src/qt/revealtxdialog.h
- Add option to open TXID in Explorer
=> [Qt] Add option to open TXID in Explorer

src/chainparams.cpp
Currently they point at a DNS that does not exist. Fix this. Adding 4 nodes.
=> [Net] Fix and Add Additional Testnet Seeds

src/main.cpp, src/main.h, src/qt/optionspage.cpp, src/qt/sendcoinsdialog.cpp, src/wallet/wallet.cpp
In preparation for the Ring Size change, add a SetRingSize function that sets the MIN_RING_SIZE / MAX_RING_SIZE variables.
In future, this will check block height and adjust Ring Size as necessary
=> [Wallet] Add SetRingSize function

src/activemasternode.cpp, src/main.cpp, src/masternodeman.cpp, src/obfuscation-relay.cpp, src/obfuscation.cpp, src/protocol.cpp, src/protocol.h
An addition to #170 - this fixes the issue with MNs not receiving some messages
=> [Net] Add and document (missed) network messages in protocol.h

src/main.cpp, src/masternode.cpp, src/masternodeman.cpp, src/wallet/wallet.cpp
Some minor updates to logging from our testnet
Improve SelectCoinsMinConf logging
Adjust logs in ReVerifyPoSBlock
Remove extra/add line breaks
=> [Trivial] Minor Logging Updates

src/net.cpp
Minor fixes to net.cpp:
- Fix incorrect return on IsReachable
- Remove extra TRY_LOCK
- Fix incorrectly set CAddress addr
- Remove extra return on IsBanned
- Remove commented/unused vfReachable
=> [Net] Minor Fixes

src/chainparams.cpp, src/chainparams.h, src/main.cpp
Change Minimum/Maximum Ring Size to 25/30
Mainnet: Block 650000
Testnet: Block 16000
=> [Consensus] Add Ring Size Hard Fork

src/chainparams.cpp
Adjust Hard Fork height to Block 700000 as we continue testing
=> [Consensus] [Hard Fork] Adjust Hard Fork height to Block 700000

src/main.cpp, src/main.h, src/rpc/blockchain.cpp
* Not used GetInputAgeIX method removed.
* Not used mapInvalidSerials variable removed.
* Not used SCRIPT_OFFSET / BIGNUM_SIZE definitions removed.
* Several for loops copying the variable cleaned.
from https://github.com/PIVX-Project/PIVX/pull/1066 with some additional cleanup
=> [Upstream] [Cleanup][Refactor][Performance] Main.cpp code cleanup:

src/main.cpp, src/txmempool.cpp, src/wallet/wallet.cpp
- Add function names
- Add more details for decoys not in same main chain / key image spent
- Add peeraddr to ProcessGetData if LogIPs is set
- Incorrect/missing line breaks/spaces
- Prevent blank error on SendToStealthAddress
- Various minor text fixes
=> [Trivial] Log updates

src/qt/forms/sendcoinsdialog.ui
Duplicate of #134 
Somehow that merge was missing the actual code change.
=> [Qt] Fix dummy balance on Send tab

src/qt/forms/sendcoinsentry.ui, src/qt/sendcoinsentry.cpp, src/qt/sendcoinsentry.h
=> [Qt] Add "Use Spendable Balance" button / Restore "Clear All" button

contrib/debian/prcycoin-qt.desktop, contrib/debian/prcycoind.service, src/qt/bitcoingui.cpp, src/qt/forms/entermnemonics.ui, src/qt/forms/importorcreate.ui, src/qt/forms/intro.ui, src/qt/forms/sendcoinsentry.ui, src/qt/locale/prcycoin_en.ts, src/qt/splashscreen.cpp
Safely rename the items we can without completely changing people's Registry locations, etc.
=> Rename to PRivaCY Coin

src/qt/askpassphrasedialog.cpp, src/qt/askpassphrasedialog.h, src/qt/forms/askpassphrasedialog.ui
=> [Qt] Add Show Passphrase checkbox to AskPassphraseDialog

src/qt/encryptdialog.cpp, src/qt/encryptdialog.h, src/qt/forms/encryptdialog.ui, src/qt/forms/optionspage.ui, src/qt/optionspage.cpp, src/qt/optionspage.h
=> [Qt] Add "Show Passphrase" to EncryptDialog and Options screen

src/init.cpp, src/main.cpp, src/main.h
> This PR mitigates the following problems:
> 
> 1. Storage of invalid PoS/zPoS blocks from forked chains.
> 2. Blocks spam filtering.
> 
> Thanks to @random-zebra for the team work on this topic.
> 
> This work will be properly detailed on the next days of QA.
from https://github.com/PIVX-Project/PIVX/pull/803
Required some additional changes to check for Key Images spent in https://github.com/PRCYCoin/PRCYCoin/commit/30d97097ed8e0fbd933be89a4d1d67a50c5ad935
=> [Upstream] [NET] Invalid blocks from forks stored on disk fix + blocks DoS spam filter. 

src/main.cpp, src/net.cpp
=> #249 Backport Corrections

src/wallet/wallet.cpp, src/wallet/wallet.h
Minor, but leftover from zerocoin
=> [Wallet] Remove fBackupMints

contrib/gitian-build.sh
> The gitian-build.sh script was broken when I've tried to use it to compile my own wallet so I've fixed it.
from https://github.com/PIVX-Project/PIVX/pull/669
Another step towards getting Gitian builds setup
=> [Upstream] [Utils] Fix syntax error in gitian-build.sh 

src/masternode-budget.cpp
These were incorrectly kept as Masternode category vs being updated to the Budget category
=> [Trivial] Use Budget log category instead of Masternode in Budgets

src/leveldb/db/db_impl.cc, src/leveldb/db/db_test.cc, src/leveldb/db/fault_injection_test.cc, src/leveldb/db/leveldbutil.cc, src/leveldb/db/log_reader.cc, src/leveldb/db/log_test.cc, src/leveldb/db/repair.cc, src/leveldb/helpers/memenv/memenv.cc, src/leveldb/include/leveldb/env.h, src/leveldb/table/format.cc, src/leveldb/table/table_test.cc, src/leveldb/util/env_posix.cc, src/leveldb/util/env_windows.cc
> Companion to #2449 that includes Unicode character support in the LevelDB side of things for windows.
from https://github.com/PIVX-Project/PIVX/pull/2495
A step towards supporting Unicode
=> [Upstream] [Core] Update LevelDB to latest upstream

src/wallet/wallet.cpp
We are repeating the same check in a number of places - this was one of the simplest offenders. We should use AvailableCoins more where possible. 
For a future PR, review all checks in AvailableCoins to be correct / make more use of it.
=> [Wallet] Remove extra checks in SelectCoins - checked in AvailableCoins

src/wallet/wallet.cpp
When using SendAll function the actual error was never being returned, just a generic one. This fixes that, adjusts some of the wording, and now logs to the debug.log as well.
=> [SendAll] Fix errors not being returned

.github/workflows/prcy-build-factory.yml, configure.ac
f5366903e2e17c2720665e41f0be1309eae8721a is a missed part of #137 
a8089fa13744140e1d56541088c00223faf6ac4b better unifies the configure for builds in our Workflow
=> [Build] [GitHub Actions] Minor Updates

src/qt/walletmodel.cpp
> auto-explainable PR from the title.
from https://github.com/PIVX-Project/PIVX/pull/1657
=> [Upstream] [GUI][Model] Remove unneeded lock in checkBalanceChanged 

src/qt/walletmodel.cpp
[Model] Use wallet pointer instead of pwalletMain -> in (future) cases where they might be more than one wallet
=> [Model] Use wallet pointer instead of pwalletMain

src/wallet/wallet.cpp
> Essentially `wallet.cpp`, `crypter.cpp` and `wallet_zerocoin.cpp` were wrongly using/calling `pwalletMain` when those files are actually THE WALLET.
> 
> This was blocking the `CWallet` object usage in unit test as the wallet (or any other wallet created that it's not `pwalletMain`) would be calling a pointer that could or couldn't exist when it should just call an internal method.
from https://github.com/PIVX-Project/PIVX/pull/1495
=> [Upstream] [Wallet] Clean wrong pwalletMain inside wallet class.

src/net.cpp
Minor follow-up to https://github.com/PRCYCoin/PRCYCoin/pull/305 that was causing a crash
=> [Net] Fix crash in ThreadMessageHandler

src/kernel.cpp, src/wallet/wallet.cpp
https://github.com/PIVX-Project/PIVX/pull/617
=> [Upstream] [Wallet] Adjust staking properties to lower orphan rates.

src/kernel.cpp, src/kernel.h, src/main.cpp, src/miner.cpp, src/stakeinput.h, src/wallet/wallet.cpp
Cherry picked staking updates from https://github.com/PIVX-Project/PIVX/pull/842
Contains some fixes as well as log spam reduction.
=> [Upstream] [Wallet] Staking Updates

src/kernel.cpp
from https://github.com/PIVX-Project/PIVX/pull/868
=> [Upstream] [Performances] Decrease the number of wasted CPU cycles

src/masternodeconfig.cpp, src/masternodeconfig.h, src/rpc/masternode.cpp
Minor fix and refactor, cherry-picked from https://github.com/PIVX-Project/PIVX/pull/1024
the rest of 1024's Consensus changes will be apart of the upcoming Hard Fork
=> [Upstream] [RPC][Refactor] Masternode Start/Broadcast

src/qt/sendcoinsdialog.cpp, src/rpc/masternode.cpp, src/rpc/server.cpp, src/rpc/server.h
`prcycoin-cli createmasternode`
```
[
{
"txhash": "Transaction-ID",
"outputidx": 0,
"genkey": "Masternode-Genkey"
}
]
```
=> [Qt][RPC] Lock Masternode Collateral on Send / Add `createmasternode` command

src/qt/res/css/Dark.css, src/qt/res/css/WebWallet.css
Fixes the whitespace surrounding Dropdown/QComboBox CSS
=> [Qt] Fix QComboBox CSS

contrib/prcycoin-qt.pro, src/Makefile.am, src/optional.h
Cherry-picked commit from https://github.com/PIVX-Project/PIVX/pull/1665
Required Class for one of the PRs I am currently backporting
=> [Upstream] `Optional` Class back port

src/wallet/wallet.cpp, src/wallet/wallet.h
Removes the secondary AvailableCoins function, in preparation for upcoming PRs.
=> [Wallet] AvailableCoins cleanup

src/wallet/wallet.cpp
These were incorrectly removed during the refactor. Restored and verified as fixed on multiple Masternodes.
=> [Wallet] Restore checks in GetVinAndKeysFromOutput

src/kernel.cpp
Bumped this up ahead of `[PoS] Stake Modifier V2`/`[PoS] Time Protocol v2` as this really spams the debug.log
from https://github.com/PIVX-Project/PIVX/pull/1233
=> [Upstream] [Trivial] Remove spammy log in in Stake

src/masternode-payments.cpp
Much cleaner FillBlockPayee function
=> [Cleanup] FillBlockPayee

src/qt/forms/historypage.ui, src/qt/historypage.cpp
includes Mined, Minted, and Masternode transactions types as Rewards
=> [Qt] Add "Rewards" category to Types on History tab

src/main.cpp, src/masternode-payments.cpp, src/masternode-payments.h
> Cleaned `IsBlockValueValid` method to be much more readable, plus removed a not needed chainActive access.
from https://github.com/PIVX-Project/PIVX/pull/1824
=> [Upstream] cleanup: IsBlockValueValid refactored properly.

src/qt/optionspage.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
It wasn't really being checked and with the upcoming Staking updates, it is not really relevant.
=> [Wallet] Remove unused walletStakingInProgress

src/qt/bitcoingui.cpp, src/qt/bitcoingui.h
Fixes a few dead links and incorrect title/function names for PRCY Toolkit after it was renamed.
=> [Qt] Various Minor Fixes

src/chainparams.cpp, src/chainparams.h, src/main.cpp
Fixes a recent issue syncing from 0.
=> [Fix] Fix syncing from 0
